### PR TITLE
Heat: Change clients endpoints on publicURL

### PR DESCRIPTION
**Pull request by mjura**
We would like to change endpoints on publicURL for Heat
and Magnum clients. This will be used by OS::Heat::WaitCondition
resource and wc_notify.

### CODE REVIEW

**Comment by jgrassler** [comment]
+1

**Comment by toabctl** [comment]
just asking - do the other clients also need this change?

**Comment by mjura** [comment]
@toabctl As @jgrassler said changing endpoints for other services can have some bad consequences.  Better would be to not change it for other services, I think.

**Comment by jgrassler** [comment]
I think I only mentioned that on IRC, so I'll provide some context just to be on the safe side:

I used to use a Heat template to create Nova flavors for quickly setting up Magnum bays in clouds without our Tempest flavors available. That ceased working a while ago because it ran afoul of the following line in Nova's `policy.json`:

https://github.com/openstack/nova/blob/stable/mitaka/etc/nova/policy.json#L145

Presumably that happened in the course of template refactoring. So in a nutshell we'll need to carefully review this kind of change for each services that base their policy decisions on the API type used. For Magnum/Heat it's fine because they do not make this distinction (Heat) or base it on authentication context rather than URL type (Magnum).

**Comment by mjura** [comment]
@jgrassler : Thank you a lot for explanations :)

**Comment by nkrinner** [comment]
+1

**Pull request merged**
