### PR TITLE
heat: revert to using older config options

### PR DESCRIPTION
**Pull request by sayalilunkad**
Tempest seems to pass with this change.

partial revert: https://github.com/crowbar/crowbar-openstack/commit/eef7a80fe8835cd9e8ea2401039bd9d532799268

(cherry picked from commit d0e707c)

### CODE REVIEW

**Comment by aplanas** [comment]
is this a cherry-pick from master? if so can we do the -x?

**Comment by sayalilunkad** [comment]
@aplanas I actually didn't need to cherry-pick because the stable branch was recently created. So I just created a new PR from my original branch. Would it be better to cherry-pick from master?

**Comment by aplanas** [comment]
No need to create a new PR, you can reuse this.

IMHO cherry-picks from master to stable provide better code management, so +1 for doing in this way for me

**Comment by sayalilunkad** [comment]
@aplanas done, thanks

**Pull request merged**
