### PR TITLE
Put global settings again into DEFAULT section

### PR DESCRIPTION
**Pull request by dirkmueller**
As part of the big cinder.conf rebase, all settings after
the backends were in the section of the last backend..

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1 tested working

**Comment by vuntz** [comment]
Just checking: having two [DEFAULT] sections is fine, and they'll be merged?

**Comment by bmwiedemann** [comment]
worked fine in our testing - e.g. ssl from the 2nd section was enabled and the backend from the first section still was used for volume create

**Comment by toabctl** [comment]
+1

**Comment by dirkmueller** [comment]
@vuntz apparently yes. we used to have one [DEFAULT] section before the great liberty rebase

**Pull request merged**
