### PR TITLE
glance: Use v2.0 auth url for glance scrubber (bsc#966924)

### PR DESCRIPTION
**Pull request by vuntz**
It's not compatible with the v3 API.

Also use the internal IP, not the public one.

https://bugzilla.suse.com/show_bug.cgi?id=966924

### CODE REVIEW

**Comment by dirkmueller** [comment]
+1. Can we improve test coverage? Scrubber is broken too often :-(

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
> Can we improve test coverage? Scrubber is broken too often :-(

Not sure why this didn't get caught with https://github.com/SUSE-Cloud/automation/pull/388 -- will check it out on Monday.

**Comment by vuntz** [comment]
>> Can we improve test coverage? Scrubber is broken too often :-(
> 
> Not sure why this didn't get caught with SUSE-Cloud/automation#388 -- will check it out on Monday.

See https://github.com/SUSE-Cloud/automation/pull/866

**Pull request merged**
