### PR TITLE
cinder: Use VIP for cinder-api haproxy config

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
LGTM codewise

**Comment by toabctl** [comment]
@aspiers any comments on this one?

**Comment by aspiers** [comment]
Looks right to me but why is this handled so inconsistently across the different barclamps?  And also why did the gate fail?

**Comment by toabctl** [comment]
> Looks right to me but why is this handled so inconsistently across the different barclamps? And also why did the gate fail?

About the PR testing failure: It's ```mount: special device /dev/vdb does not exist``` which should be addressed by https://github.com/SUSE-Cloud/automation/pull/563

About the inconsistently: No idea.

**Pull request merged**
