### PR TITLE
Refactor optional repo check

### PR DESCRIPTION
**Pull request by rsalevsky**
This change makes it easier to handle all the diffrent cases in the UI.

### CODE REVIEW

**Comment by dirkmueller** [comment]
@rsalevsky typo optional in commit message

**Comment by jsuchome** [comment]
Good in general, but the functions can return false in 2 different cases. How will user know the difference?

**Comment by rsalevsky** [comment]
@jsuchome Fixed, the `if ... else ... end` was anyway not needed.

**Comment by jsuchome** [comment]
+1

**Comment by vuntz** [comment]
+1

**Pull request merged**
