### PR TITLE
use the new locking routines

### PR DESCRIPTION
**Pull request by MaximilianMeister**
introduced by and dependent on https://github.com/crowbar/crowbar-core/pull/5

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
@rsalevsky @tboerger wtf is going on with the hound?

first I had
```ruby
Crowbar::Lock.new(
  logger: @logger,
  path: Rails.root.join("tmp", "#{@bc_name}.lock")
```
`Style/AlignHash: Align the elements of a hash literal if they span more than one line.`

then i used autocorrect to make it look like
```ruby
Crowbar::Lock.new(
  logger: @logger,
  path:   Rails.root.join("tmp", "#{@bc_name}.lock")
```
`Style/ExtraSpacing: Unnecessary spacing detected.`

so I used autocorrect once again and guess what I got.

this is just an endless loop...

**Comment by tboerger** [comment]
Looks like local rubocop got other defaults than houndci for this specific case.

**Comment by tboerger** [comment]
I pike that, beside the houndci complains :+1:

**Comment by vuntz** [comment]
Is this valid (since https://github.com/crowbar/crowbar-core/pull/14 looks different now)?

**Comment by aspiers** [comment]
No, it needs reworking but it's a simple change.

**Comment by vuntz** [comment]
This can be updated to the new way as https://github.com/crowbar/crowbar-core/pull/14 got merged.

**Comment by aspiers** [comment]
Damn, I forgot about this :-(

**Comment by aspiers** [comment]
Superseded by #37.

**Pull request closed without merging**
