### PR TITLE
Added rubocop config to map to hound config

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by dirkmueller** [comment]
whats the rationale for this change?

**Comment by tboerger** [comment]
> whats the rationale for this change?

The same as https://github.com/crowbar/crowbar-core/pull/443 make it possible to use rubocop-git useable without any additional parameters.

**Comment by tboerger** [comment]
@dirkmueller I have extended the commit message.

**Comment by tboerger** [comment]
Merge?

**Comment by tboerger** [comment]
I'm merging this now as openstack is the only component with this PR still open.

**Pull request merged**
