### PR TITLE
tempest: add missing parameters for xen hosts

### PR DESCRIPTION
**Pull request by Itxaka**

### CODE REVIEW

**Comment by Itxaka** [comment]
Triggered a manual mkcloud run with xen livbirt_type to test it

**Comment by sayalilunkad** [comment]
Can you add the bug number in the commit message

**Comment by sayalilunkad** [comment]
isn't it bsc#1017597?

**Comment by Itxaka** [comment]
good point @sayalilunkad, will update the commit message before merging, so I dont need to relaunch the ci jobs again :)

**Pull request merged**
