### PR TITLE
nova: Change grub config after xen kernel is installed

### PR DESCRIPTION
**Pull request by vuntz**
The code to change the grub config is parsing the list of available
kernels, but since it was running in the compilation phase, it had to
reboot twice to actually work as intended. So run this in the
convergence phase with a ruby_block.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
No code change, just rephrased the commit to be clearer.

**Comment by rsalevsky** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
Still +1

**Pull request merged**
