### PR TITLE
horizon: Rename remaining nova-dashboard files to openstack-dashboard

### PR DESCRIPTION
**Pull request by vuntz**
This completes the move away from nova-dashboard name.

### CODE REVIEW

**Comment by dirkmueller** [comment]
+1

**Comment by rhafer** [comment]
+1

**Comment by rsalevsky** [comment]
@vuntz I know it's not your fault but can you fix the hound issue as an separate commit?

**Comment by vuntz** [comment]
@rsalevsky done

**Comment by rsalevsky** [comment]
thanks :+1:

**Pull request merged**
