### PR TITLE
[4.0] database: Move PostgreSQL settings above MySQL

### PR DESCRIPTION
**Pull request by skazi0**
Both database forms can be shown at the same time now so order is
more important. PostgreSQL is the "old" engine so it should be on top.

Will need a rebase after #1705 is merged

### CODE REVIEW

**Review by jsuchome — APPROVED** [review]

**Review by jhesketh — APPROVED** [review]

**Comment by rsalevsky** [comment]
I would argue different and would place MySQL on top as we want everyone to use MySQL. Further I would place a depreciation warning on top of PostgreSQL-

**Comment by jsuchome** [comment]
The point is that this is intended for SOC7 where users already have PostgreSQL. With our new set of patches they will be able to apply mariadb, but not remove postgres, that's a preparation for migration step.
I find it more logical to see on top the stuff that is already deployed and new options below.

**Comment by rsalevsky** [comment]
If there is already a database deployed then this makes sense, can we easily switch the default behavior to something like: If a no database or MariaDB is deployed or show MariaDB first otherwise show PostgreSQL first?

**Comment by jsuchome** [comment]
For such kind of logic there's https://github.com/crowbar/crowbar-openstack/pull/1705 ... you can follow the discussion out there.

**Comment by rsalevsky** [comment]
Thanks, I will follow-up there.

**Pull request closed without merging**
