### PR TITLE
Revert "tempest: Temporary disable manila tests"

### PR DESCRIPTION
**Pull request by toabctl**
This reverts commit 2d27de339d69f5a6ea938d38632563e0e3994d76.

### CODE REVIEW

**Comment by toabctl** [comment]
At least locally smoke tests passed for me. Let's see what gating says...

**Comment by toabctl** [comment]
It's broken because of a missing share type. Fix is https://github.com/SUSE-Cloud/automation/pull/819

**Comment by toabctl** [comment]
Ok. So the smoke tests pass with linuxbridge+vlan but fail with openvswitch. That's something I recognized and debugged with @rhafer . So our openvswitch+vlan setup needs to be fixed.

**Comment by vuntz** [comment]
So after some discussion on IRC, I understand that this only works with linuxbridge. If that's correct, then we can't merge yet because that would break gating (which is using ovs)

**Comment by toabctl** [comment]
> So after some discussion on IRC, I understand that this only works with linuxbridge. If that's correct, then we can't merge yet because that would break gating (which is using ovs)

Correct. Tests passed because I changed the job to use linuxbridge+vlan.

**Comment by toabctl** [comment]
Currently blocked by https://github.com/SUSE-Cloud/automation/pull/824

**Comment by toabctl** [comment]
@vuntz now it passed also with openvswitch. Still only smoke tests but if that's ok, this is ready to be merged

**Comment by vuntz** [comment]
+1

**Comment by mjura** [comment]
+1

**Comment by aplanas** [comment]
+1

**Pull request merged**
