### PR TITLE
nova: Fix ipaddress attribute

### PR DESCRIPTION
**Pull request by cmurphy**
This is @sayalilunkad 's PR, but she is on vacation and it was posted a while ago and jenkins has deleted its UPDATEREPO. I'd like to rebuild it but I can't force push to her branch so I'm resubmitting the PR.

### CODE REVIEW

**Comment by cmurphy** [comment]
```
16:55:23 +(qa_crowbarsetup.sh:3935) oncontroller_testsetup(): crm_mon --failcounts -1
16:55:23 +(qa_crowbarsetup.sh:3935) oncontroller_testsetup(): grep fail-count=
16:55:23    vip-admin-database-default-data: migration-threshold=3 fail-count=1 last-failure='Wed Mar 22 15:38:16 2017'
16:55:23    vip-admin-rabbitmq-default-data: migration-threshold=3 fail-count=1 last-failure='Wed Mar 22 15:38:17 2017'
16:55:23 +(qa_crowbarsetup.sh:3935) oncontroller_testsetup(): complain 55 'Cluster resources'\'' failures detected'
```

**Comment by s-t-e-v-e-n-k** [comment]
@aspiers I'm curious for your take on this PR. Given the error that @cmurphy pasted above, it looks like we require a perfect setup with no failures when deploying for CI, but whenever I've done deploys in a HA situation, failures crop up and are handled with the services running.

**Comment by cmurphy** [comment]
Okay here's the breakdown of this gate failure.

Unfortunately the chef client logs in the support config only go back 10000 lines and they don't include what happened just before 15:38:16 when the pacemaker recovered from the failure, so I reproduced it locally. For me crm_mon reports

```
Failed Actions:
* vip-admin-database-default-data_monitor_10000 on d52-54-77-77-01-01 'not running' (7)
: call=32, status=complete, exitreason='none',
    last-rc-change='Thu Mar 23 10:13:42 2017', queued=0ms, exec=0ms
* vip-admin-rabbitmq-default-data_monitor_10000 on d52-54-77-77-01-01 'not running' (7)
: call=55, status=complete, exitreason='none',
    last-rc-change='Thu Mar 23 10:13:42 2017', queued=0ms, exec=0ms
```

Okay, something happened right around 10:13. In syslog there is:

```
2017-03-23T10:13:37.742246+00:00 d52-54-77-77-01-01 wickedd[773]: eth0: No duplicates for I
P address 192.168.215.84 detected
2017-03-23T10:13:37.773628+00:00 d52-54-77-77-01-01 wickedd[773]: eth0: Notified neighbours about IP address 192.168.215.84
```

and in the chef logs:

```
[2017-03-23T10:13:36+00:00] INFO: ruby_block[wicked-ifreload-required] called
```

So that leads me to https://github.com/crowbar/crowbar-core/pull/1150 which merged right around the time our HA tests started failing. The failure in that PR was related to DRBD so it never made it up to the point where it would have failed because of the network reload.

So indeed it goes back to what @s-t-e-v-e-n-k is asking, should our HA tests be tolerant of this? Or maybe we should be reordering things somehow so that wicked gets reloaded before the vip resources get created?

**Comment by cmurphy** [comment]
And by the way it's happening during the keystone proposal

```
Starting proposal keystone(default) at: Thu Mar 23 11:13:10 CET 2017
```

**Comment by cmurphy** [comment]
More discovery:

Keystone is the first openstack service to set up vip networks for haproxy:

https://github.com/crowbar/crowbar-openstack/blob/release/suse-openstack-cloud/7/crowbar_framework/app/models/keystone_service.rb#L115-L118

The public network uses vlan tag 300:

https://github.com/crowbar/crowbar-core/blob/release/suse-openstack-cloud/7/chef/data_bags/crowbar/template-network.json#L166

so chef creates the vlan interface:

```
[2017-03-23T10:13:27+00:00] INFO: Creating vlan eth0.300 for network public
[2017-03-23T10:13:27+00:00] INFO: Creating new VLAN interface eth0.300
Set name-type for VLAN subsystem. Should be visible in /proc/net/vlan/config
Added VLAN with VID == 300 to IF -:eth0:-
[2017-03-23T10:13:27+00:00] INFO: Returning new VLAN interface #<Nic::Vlan:0x00000005110a80 @nic="eth0.300", @nicdir="/sys/class/net/eth0.300", @addresses=[], @dependents=nil>
```

which triggers the wickedd reload.

**Comment by cmurphy** [comment]
Proposing https://github.com/SUSE-Cloud/automation/pull/1802 in agreement with Steve, this should be considered expected behavior

**Comment by s-t-e-v-e-n-k** [comment]
Current hacloud failure looks like haproxy was reloaded (or failed and recovered), but the timestamp for the fail action seems very strange -- was before any haproxy using services were deployed.

**Comment by cmurphy** [comment]
@s-t-e-v-e-n-k how do you figure that? The first haproxy service is keystone:

```
09:37:16 proposal keystone successful
```

and the failure was 43 minutes later

```
11:04:26    haproxy: migration-threshold=3 fail-count=1 last-failure='Sat Mar 25 10:10:07 2017'
```

I think this is probably another symptom of the same problem.

**Comment by cmurphy** [comment]
Oh, the CET -> UTC might be confusing me...

**Comment by s-t-e-v-e-n-k** [comment]
I was assuming that all times in the logs were the same timezone.

proposal keystone successful
Proposal exit code: 0
Finished proposal keystone(default) at: Sat Mar 25 10:37:16 CET 2017

haproxy: migration-threshold=3 fail-count=1 last-failure='Sat Mar 25 10:10:07 2017'

so then how did haproxy fail approximately 25 minutes before it was deployed ...

**Comment by cmurphy** [comment]
Looking at the support configs it looks like the crowbar node is in CET, which is where the Starting/Finished print statements run, but the other nodes as well as the build host are in UTC, so the keystone proposal actually finished at 09:37:16 UTC, so it makes sense for haproxy to have failed some time after that.

**Comment by s-t-e-v-e-n-k** [comment]
So based on the log:

proposal horizon successful
Proposal exit code: 0
Finished proposal horizon(default) at: Sat Mar 25 11:08:22 CET 2017

Starting proposal ceilometer(default) at: Sat Mar 25 11:08:33 CET 2017
Edited default
Committed default
Commit exit code: 0
Waiting for proposal ceilometer(default) to get successful: Waiting for: proposal to be successful
  until this condition is true: proposalstatus=`onadmin_get_proposalstatus ceilometer default` ; [[ $proposalstatus =~ success|failed ]]
  waiting 800 cycles of 1 seconds = 800 seconds

proposal ceilometer successful
Proposal exit code: 0
Finished proposal ceilometer(default) at: Sat Mar 25 11:17:58 CET 2017

So if my timezone maths is correct, I wonder if the ceilometer barclamp is to blame.

**Comment by cmurphy** [comment]
Something is causing the haproxy service to refresh on the second controller:

```
2017-03-25T10:10:07.565497+00:00 d52-54-77-77-01-02 systemd[1]: Reloading Cluster Controlled haproxy.
2017-03-25T10:10:07.711501+00:00 d52-54-77-77-01-02 systemd[1]: Reloaded Cluster Controlled haproxy.
2017-03-25T10:10:07.711801+00:00 d52-54-77-77-01-02 haproxy-systemd-wrapper[32645]: haproxy-systemd-wrapper: re-executing on SIGUSR2.
2017-03-25T10:10:07.731312+00:00 d52-54-77-77-01-02 haproxy-systemd-wrapper[32645]: haproxy-systemd-wrapper: executing /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -Ds -sf 9765
2017-03-25T10:10:07.849768+00:00 d52-54-77-77-01-02 lrmd[25053]:   notice: executing - rsc:neutron-ha-tool action:stop call_id:425
2017-03-25T10:10:07.897504+00:00 d52-54-77-77-01-02 lrmd[25053]:   notice: finished - rsc:neutron-ha-tool action:stop call_id:425 pid:17610 exit-code:0 exec-time:47ms queue-time:1ms
2017-03-25T10:10:07.898200+00:00 d52-54-77-77-01-02 crmd[25056]:   notice: Result of stop operation for neutron-ha-tool on d52-54-77-77-01-02: 0 (ok)
2017-03-25T10:10:07.903523+00:00 d52-54-77-77-01-02 lrmd[25053]:   notice: executing - rsc:haproxy action:stop call_id:427
```

Unfortunately the support config doesn't include the chef logs from that early in the run.

**Comment by cmurphy** [comment]
@rhafer here's the bug report for the gateway issue: https://bugzilla.suse.com/show_bug.cgi?id=1031077

I'm concerned that I haven't seen other jobs with this particular failure but I suppose that's because the other problems have prevented them from getting this far.

**Pull request merged**
