### PR TITLE
heat: Minify heat.conf template

### PR DESCRIPTION
**Pull request by dirkmueller**
remove all comments and whitespace in prepration of Newton port

### CODE REVIEW

**Comment by nicolasbock** [comment]
This comment is not meant as a criticism, I am just curious: how does this minification help in the Newton port?

**Comment by toabctl** [comment]
nit: commit msg should start with ```heat:```

**Comment by dirkmueller** [comment]
@nicolasbock its part of the grant master plan to only set those settings that we need to be set.. I thought it is easier to get the comment-deletion part in before we actually look at the templates.

**Comment by jgrassler** [comment]
@aplanas: Yes, that's the plan eventually. But this is just a preparatory first step to make sorting the rest out later easier (no useless comments to sift through).

**Comment by aplanas** [comment]
@jgrassler sorry, I do not get it. I was thinking that this exercise with Heat was to test the new layout in a isolated way. Part of the test was moving the new clean config file to the new house. Did I missunderstand this?

**Comment by jgrassler** [comment]
@aplanas:
| remove all comments and whitespace in prepration of Newton port

I understand this as "remove irrelevant noise" so the actual work of testing the new layout requires less scrolling.

**Comment by nicolasbock** [comment]
@dirkmueller Thanks. It definitely is a lot more readable without the comments :)

**Comment by dirkmueller** [comment]
@aplanas yes, but I wanted to do that in a separate pull request (to isolate signal from noise)

**Comment by dirkmueller** [comment]
@aplanas added the move.. will likely not work right now as the packaging changes for that are not yet in the tree.

**Comment by toabctl** [comment]
retriggered gating

**Pull request merged**
