### PR TITLE
Removes public endpoint from keystone conf (bsc#954957)

### PR DESCRIPTION
**Pull request by sayalilunkad**
Removing the public endpoint fixes the issue of mismatched endpoints.

### CODE REVIEW

**Comment by dirkmueller** [comment]
I'd appreciate if you'd update the config file template as well. I'm btw don't undersand the explanation on why this is a good change.

**Comment by sayalilunkad** [comment]
@dirkmueller  maybe this will explain better as to why we need this change https://bugs.launchpad.net/mos/+bug/1508489

**Comment by dirkmueller** [comment]
@sayalilunkad thanks for the link, please add the explanation to the git commit message

**Comment by mjura** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Comment by rhafer** [comment]
I must admit I am not fully getting it. But AFAIU this change is ok. 

+ 0.99

**Pull request merged**
