### PR TITLE
nova: Fix call to non existing method (caused by f064ae87)

### PR DESCRIPTION
**Pull request by vuntz**
cc @dirkmueller

### CODE REVIEW

**Comment by rsalevsky** [comment]
After the hound message is fixed +1

**Comment by vuntz** [comment]
Hound is happy now (and I fixed the error message which was broken...)

**Comment by aplanas** [comment]
+1

**Comment by bmwiedemann** [comment]
+1 - mkcloud had passed with kvm but failed to boot the VM with xen (maybe unrelated)

**Comment by vuntz** [comment]
Deployment work in gating; since the code is really just in the validation of the proposal, that should be good enough even though tempest failed (which is due to failures related to xen).

**Comment by toabctl** [comment]
+1

**Pull request merged**
