### PR TITLE
Some work for compatibility with chef 11

### PR DESCRIPTION
**Pull request by vuntz**
This is mostly about changing "node[:foo] =" to "node.set[:foo] ="

### CODE REVIEW

**Comment by rsalevsky** [comment]
Looks good so far but the hound needs some attention.

**Comment by tboerger** [comment]
Some offenses can be fixed, otherwise :+1:

**Comment by vuntz** [comment]
I added a commit to help with hound, not sure if we really want to fix the "line too long" ones (would require adding some temporary variable just for this). @rsalevsky @tboerger what do you think?

**Comment by mjura** [comment]
@vuntz : I had this same discussion last week with @rsalevsky about "Line too long". I'm voting for check fir lines with 150 characters.

@tboerger : What would you say about this?

**Comment by aplanas** [comment]
Is this change of `default` and `.set` valid for chef 10? Or is expected problems once is merged?

**Comment by vuntz** [comment]
> Is this change of default and .set valid for chef 10? Or is expected problems once is merged?

Good that you're asking :-) It is compatible (things that were not default `default` are actually a bug, `.set` is just implicit in Chef 10).

Gating seems to agree.

**Comment by aplanas** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
