### PR TITLE
nova: Do not do partial online migrations, that was Newton specific

### PR DESCRIPTION
**Pull request by jsuchome**
We needed to do step by step upgrade (sync up to certain version + online migrations + new synce + new online migrations) when upgrading
to Newton. This code should not be needed any more in master branch.

I *think* this is correct, but it's not yet tested neither during installation nor during upgrade... 
**UPDATE** gating success confirms that it does not break normal installation...

### CODE REVIEW

**Comment by jsuchome** [comment]
Works for me during the upgrade as well. 

I did have 3 instances running before the upgrade, but I'm not sure if those potentially problematic tables had any entries on Newton side.

**Comment by jsuchome** [comment]
@jgrassler @matthewoliver please see 2nd commit.

Alternatively, I can subscribe the action to different block by
`subscribes :create, "execute[nova-manage cell_v2 map_instances]", :immediately`

But somehow I do not see a reason why we're using `:immediately` in this place.

**Comment by jgrassler** [comment]
The `:immediately` seems superfluous indeed, but as long as it works I'd lean towards leaving it in there.

**Comment by jsuchome** [comment]
@jgrassler so it seems current state works well with installation, and worked for me during upgrade as well

**Comment by jsuchome** [comment]
@jgrassler @matthewoliver another round of review please?

**Pull request merged**
