### PR TITLE
tempest: Replace keystone CLI calls with openstack

### PR DESCRIPTION
**Pull request by toabctl**
keystone CLI is depreacted and will be removed in Newton. So switch
to the replacement which is openstack.
Also simplifiy a bit the getters for ec2 access and secret.

### CODE REVIEW

**Comment by vuntz** [comment]
LGTM

**Comment by sayalilunkad** [comment]
Looks good to go unless CI catches problem!

**Comment by jgrassler** [comment]
The code looks good to me, so +1 provided gating passes (the gating failure (`14:24:20 Error: 'crowbar provisioner proposal --file=/root/provisioner.default.proposal edit default' failed with exit code: 1`) looked unrelated, gate job restarted).

**Comment by sayalilunkad** [comment]
So seems like EC2 credentials are not found..

Recipe Compile Error in /var/chef/cache/cookbooks/tempest/recipes/role_tempest.rb


RuntimeError

Cannot fetch EC2 credentials 

Cookbook Trace:

  /var/chef/cache/cookbooks/tempest/recipes/config.rb:272:in `from_file'
  /var/chef/cache/cookbooks/tempest/recipes/role_tempest.rb:19:in `from_file'

Relevant File Content:

/var/chef/cache/cookbooks/tempest/recipes/config.rb:

265:      "OS_USER_DOMAIN_NAME" => keystone_settings["api_version"] != "2.0" ? "Default" : "",
266:      "OS_PROJECT_DOMAIN_NAME" => keystone_settings["api_version"] != "2.0" ? "Default" : ""
267:    })
268:  end
269:  
270:  ec2_access = `#{openstackcli} ec2 credentials list -f value -c Access`.strip
271:  ec2_secret = `#{openstackcli} ec2 credentials list -f value -c Secret`.strip
272>> raise("Cannot fetch EC2 credentials ") if ec2_access.empty? || ec2_secret.empty?

**Comment by sayalilunkad** [comment]
+1

**Comment by rhafer** [comment]
+1

**Pull request merged**
