### PR TITLE
Ceilometer tempest

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by toabctl** [comment]
This will fail for now (package update on the way and there is a race in one tempest test)

**Comment by aplanas** [comment]
re-trigger the gating, but codewise +1

**Comment by toabctl** [comment]
> re-trigger the gating, but codewise +1

it can not pass. The packages need to pass cleanvm first.

**Comment by vuntz** [comment]
+1, let's just wait for gating :-)

**Comment by toabctl** [comment]
I still had a race condition with deleting the security groups in the tearDown function. Let's see if we get this in the gating, too.

**Comment by toabctl** [comment]
@aplanas @vuntz tempest passed (with 2 ceilometer tests, wow! :)) . Can be merged imo....

**Comment by vuntz** [comment]
> with 2 ceilometer tests

Hrm, shouldn't we expect to have more tests?

**Comment by toabctl** [comment]
> Hrm, shouldn't we expect to have more tests?

There are 4 api tests in total and only 2 of them are smoke tests. See https://github.com/openstack/ceilometer/blob/master/ceilometer/tests/tempest/api/test_telemetry_notification_api.py . And there's anotherr scenario test (non-smoke). So looks ok.

**Comment by aplanas** [comment]
+1 then

**Pull request merged**
