### PR TITLE
Added support for Aodh, new stand-alone alarming service.

### PR DESCRIPTION
**Pull request by jsuchome**
Aodh replaces old ceilometer alarming services in Mitaka

### CODE REVIEW

**Comment by jsuchome** [comment]
Seems to work so far, HA support still missing...

**Comment by vuntz** [comment]
Wondering out loud: wouldn't it be cleaner to have a aodh cookbook? (not a barclamp, just a cookbook that would be used by the barclamp)

**Comment by jsuchome** [comment]
I thought about it, but haven't decided yet. It's really tied to ceilometer (also ceilometer server node).

**Comment by jsuchome** [comment]
... but it would solve the ugly hacks while fetching `network_settings`, and also with `CrowbarPacemakerHelper.haproxy_servers_for_service`

**Comment by jsuchome** [comment]
Yes, https://github.com/crowbar/crowbar-openstack/pull/371 looks better

**Pull request closed without merging**
