### PR TITLE
nova: Revert vmware compute nodes don't need direct access to networking

### PR DESCRIPTION
**Pull request by mjura**
This revert partially commit 6b20c0b

### CODE REVIEW

**Comment by vuntz** [comment]
If @rhafer is fine with it, +1 from me.

**Comment by dirkmueller** [comment]
could you do a git revert on the git commits directly?

**Comment by rhafer** [comment]
If this is what is needed I am fine with it.

Though I am really wondering why vmware would need the layer 2 agents running on the compute proxy. It just seems weird and I am pretty sure the vmware instances are not sending any traffic through that. @mjura can you clarify that a bit. (There doesn't seem to be much upstream doc on this)

**Comment by mjura** [comment]
>Though I am really wondering why vmware would need the layer 2 agents running on the compute proxy. It just seems weird and I am pretty sure the vmware instances are not sending any traffic through that. @mjura can you clarify that a bit. (There doesn't seem to be much upstream doc on this)

I guess that it is because neutron-server is trying to create network Port on hypervisor site and because it can't create it on ESXi (no possible to run neutron agents on ESXi side). Network port is created on nova-compute proxy to return proper status to neutron. For me it looks that it is illogical but I think that it was implemented in this way.
```
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager [-] Instance failed network setup after 1 attempt(s)
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager Traceback (most recent call last):
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/compute/manager.p
y", line 1564, in _allocate_network_async
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager     dhcp_options=dhcp_options)
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/network/neutronv2
/api.py", line 744, in allocate_for_instance
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager     self._delete_ports(neutron, instance, created_port_ids)
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 195, in __exit__
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager     six.reraise(self.type_, self.value, self.tb)
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py", line 736, in allocate_for_instance
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager     security_group_ids, available_macs, dhcp_opts)
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py", line 359, in _create_port
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager     raise exception.PortBindingFailed(port_id=port_id)
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager PortBindingFailed: Binding failed for port 64a42751-59ad-4588-be12-2f58ccb9d432, please check neutron logs for more information.
2016-02-17 08:50:43.395 26825 ERROR nova.compute.manager 
```

**Comment by mjura** [comment]
First change
https://github.com/crowbar/crowbar-openstack/pull/296

**Comment by mjura** [comment]
@dirkmueller : I splitted this PR into two changes which are reverting changes for VMware https://github.com/crowbar/crowbar-openstack/pull/296

**Comment by dirkmueller** [comment]
@mjura can you add bug reference to the git commit message?

**Comment by mjura** [comment]
@dirkmueller : I've added bug number to commit message

**Comment by dirkmueller** [comment]
+1

**Comment by dirkmueller** [comment]
rhafer already said he's fine, so merging..

**Pull request merged**
