### PR TITLE
Create base of Cloud 7 Upgrade API V2 for crowbar-openstack

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by mjura** [comment]
+1

**Comment by MaximilianMeister** [comment]
stripped the `/v2` from the url. the version will be sent now through the accept header

**Comment by vmoravec** [comment]
@MaximilianMeister What is the reason to prefer api version in accept header to put it in the url?

**Comment by MaximilianMeister** [comment]
> @MaximilianMeister What is the reason to prefer api version in the accept header to putting it in the url?

@kirushik gave some good explanation in https://github.com/crowbar/crowbar-core/pull/555#issuecomment-237294140 (hope that answers the question good enough)

...it doesn't mention the url bit though, which I thought would be repetitive information when we send a version through the header anyway.

**Comment by mjura** [comment]
Gating is failing, because of
```
echo 'Error: Waiting for '\''crowbar service to start'\'' timed 
```

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xeN0LnPm&#x2F;95-5-s47p9-implement-api-for-preparing-nodes-for-upgrade-upgrade-step-2"> (5) S47P9 Implement API for preparing nodes for upgrade (upgrade step 2)</a>

**Pull request merged**
