### PR TITLE
Revert "tempest: Temporary disable manila tests"

### PR DESCRIPTION
**Pull request by toabctl**
Reverts crowbar/crowbar-openstack#213

### CODE REVIEW

**Comment by vuntz** [comment]
@toabctl does that mean that all manila tempest tests are passing (not just smoke tests)?

**Comment by toabctl** [comment]
@vuntz I don't know. I created this to see if the smoke tests pass. Adding the WIP label...

**Comment by vuntz** [comment]
Ah, makes sense, thanks :-)

**Comment by toabctl** [comment]
@dirkmueller any idea why the PR doesn't trigger a gating build here?

**Comment by vuntz** [comment]
@toabctl I retriggered gating.

**Comment by toabctl** [comment]
@vuntz thanks. But I recognized it depends on https://github.com/crowbar/crowbar-openstack/pull/230

**Comment by toabctl** [comment]
@vuntz no gating, again. What's wrong here? I need gating with this patch on top of current master...

**Comment by vuntz** [comment]
@toabctl re-triggered. Not sure what you did to jenkins that made it ignore you ;-)

**Comment by toabctl** [comment]
I'll recreate a new PR when it's ready...

**Comment by toabctl** [comment]
@vuntz will be continued here: https://github.com/crowbar/crowbar-openstack/pull/247

**Pull request closed without merging**
