### PR TITLE
horizon: Install Neutron Lbaas plugin for dashboard

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by mjura** [comment]
Gating is failing because package is not yet in `develcloud7` repo

**Comment by toabctl** [comment]
> Gating is failing because package is not yet in develcloud7 repo

Hopefully fixed with the next image.

**Comment by mjura** [comment]
I've re-triggered gating test, package is already there

**Comment by mjura** [comment]
I've tested this PR manually and works great

**Pull request merged**
