### PR TITLE
Backport support for LBaaSv2, F5 LBaaS and explicit enablement of l2pop

### PR DESCRIPTION
**Pull request by vuntz**
All of this is actually required just for F5.

This is a backport of:
- https://github.com/crowbar/crowbar-openstack/pull/513 (excluding two commits) [merged]
- https://github.com/crowbar/crowbar-openstack/pull/583 [merged]
- https://github.com/crowbar/crowbar-openstack/pull/565 (excluding one commit) [merged]
- https://github.com/crowbar/crowbar-openstack/pull/750 [merged]
- https://github.com/crowbar/crowbar-openstack/pull/386 [merged]
- https://github.com/crowbar/crowbar-openstack/pull/751 [merged]
- https://github.com/crowbar/crowbar-openstack/pull/753 [merged]
- https://github.com/crowbar/crowbar-openstack/pull/754 [merged]
- https://github.com/crowbar/crowbar-openstack/pull/756 [merged]

### CODE REVIEW

**Comment by vuntz** [comment]
This is ready (from my perspective) but we should probably not merge until all the PRs this backports are merged.

**Comment by vuntz** [comment]
All PR for master are merged, so this could be merged now. Just missing reviews.

**Comment by aplanas** [comment]
The gating fail was hopefully fixed. Re-triggering the job.

**Comment by vuntz** [comment]
Rebased, as I believe the gating issue may be related to some missing swift bits in my branch.

**Comment by rsalevsky** [comment]
After this is merged I will prepare the next maintenance update.

**Comment by vuntz** [comment]
@aplanas are you still +1 on this? (asking because I had to rebase after your +1)

**Pull request merged**
