### PR TITLE
nova proposal UI: Change Datastore Name

### PR DESCRIPTION
**Pull request by mjura**
Regex to match the name of a datastore.

This was reported to documentation too
https://github.com/SUSE-Cloud/doc-cloud/pull/15

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
+1

**Comment by vuntz** [comment]
Can you backport to 3.0? +1.

**Comment by vuntz** [comment]
Actually, can you change "Regex" to "Regular Expression"?

**Comment by mjura** [comment]
Change was backported to `crowbar/3.0` https://github.com/crowbar/crowbar-openstack/pull/328

**Comment by mjura** [comment]
@vuntz I fixed your comment

**Comment by mjura** [comment]
Thank you

**Comment by MaximilianMeister** [comment]
+1 again

**Comment by vuntz** [comment]
Thanks.

**Pull request merged**
