### PR TITLE
Tempest conf manila

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by toabctl** [comment]
@dirkmueller please comment on the "Files changed" section. Comments on commits are difficult to find ...

**Comment by dirkmueller** [comment]
+1

**Comment by mjura** [comment]
+1

**Comment by vuntz** [comment]
I'm fine merging this, but I wonder if the settings should be exposed in the UI since they seem to be required to get things to work properly.

**Comment by vuntz** [comment]
We agreed to do the UI in a followup PR.

**Pull request merged**
