### PR TITLE
Rename horizon.rb to horizon_service.rb

### PR DESCRIPTION
**Pull request by rhafer**
To be consistent with all the other Service models. Seems it got wrong with the
nova_dashboard -> horizon rename.

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by vwallfahrer** [comment]
+1

**Comment by toabctl** [comment]
-1 . Seems to be a patch in the package for ```horizon.rb```. From the log: ```patching file crowbar_framework/app/models/horizon.rb```

**Comment by vuntz** [comment]
@toabctl that's prtest.patch :-) I think the gating just doesn't deal properly with renaming in patches?

**Pull request merged**
