### PR TITLE
ceilometer: Change template to new use new conf dir

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by Itxaka** [comment]
Also missing in ceilometer central recipe:

```
00:44:43.367 Relevant File Content:
00:44:43.367 ----------------------
00:44:43.367 /var/chef/cache/cookbooks/ceilometer/recipes/central.rb:
00:44:43.367 
00:44:43.367  24:  
00:44:43.367  25:  ha_enabled = node[:ceilometer][:ha][:central][:enabled]
00:44:43.367  26:  
00:44:43.367  27:  service "ceilometer-agent-central" do
00:44:43.367  28:    service_name node[:ceilometer][:central][:service_name]
00:44:43.367  29:    supports status: true, restart: true, start: true, stop: true
00:44:43.367  30:    action [:enable, :start]
00:44:43.367  31>>   subscribes :restart, resources("template[/etc/ceilometer/ceilometer.conf]")
00:44:43.367  32:    subscribes :restart, resources("template[/etc/ceilometer/pipeline.yaml]")
00:44:43.367  33:    provider Chef::Provider::CrowbarPacemakerService if ha_enabled
00:44:43.367  34:  end
```

**Comment by Itxaka** [comment]
also missing on the agent recipe

**Comment by nicolasbock** [comment]
I have added the line @Itxaka suggested and found another one. Let's see if gating is passing now.

**Comment by nicolasbock** [comment]
Gating is passing. Someone else with write access needs to approve this before we can merge.

**Pull request merged**
