### PR TITLE
swift: Create container-sync-realms.conf on proxy nodes too

### PR DESCRIPTION
**Pull request by vuntz**
The file is needed not just on container/storage nodes, but also on the
proxy node.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

is planned to make the number `realms` configurable?

**Comment by jsuchome** [comment]
+1 (Do we have a bug report? Or some failure indicating that it's missing on proxy  nodes?)

**Comment by vuntz** [comment]
> (Do we have a bug report? Or some failure indicating that it's missing on proxy nodes?)

https://ci.suse.de/job/openstack-mkcloud/14923/artifact/.artifacts/tempest.log

**Comment by vuntz** [comment]
> is planned to make the number realms configurable?

It's what I mentioned in https://github.com/crowbar/crowbar-openstack/commit/0749ce0f7e532b929f394eb64b0eeff68208ba1d

I'm not exactly sure how people will want to use that, so for now it's only one realm with a default config that is not super useful.

**Pull request merged**
