### PR TITLE
cinder, glance: Install qemu-img only when needed

### PR DESCRIPTION
**Pull request by vuntz**
qemu-img is used by some bits of both cinder and glance.

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by toabctl** [comment]
Why not adding it as a Requires to the package?

**Comment by vuntz** [comment]
@toabctl good point, will do that and check if other distros have the dep too.

**Comment by vuntz** [comment]
@toabctl updated

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
