### PR TITLE
Fix mistakes from rabbitmq SSL addition

### PR DESCRIPTION
**Pull request by cmurphy**
This patch bumps the schema revision for the rabbitmq databag to 100 and
adds missing oslo_messaging_rabbitmq settings to the glance registry
configuration.

### CODE REVIEW

**Comment by dirkmueller** [comment]
Rename the migration file to 100_... as well?

**Comment by cmurphy** [comment]
@dirkmueller woops, done

**Comment by dirkmueller** [comment]
Git commit message summary should start with ```glance: ...``` and maybe more generic (the summary appears in the changelog)

**Comment by cmurphy** [comment]
Split into two commits to address the mistakes separately

**Comment by rsalevsky** [comment]
LGTM, the original "mistake" is not in the current crowbar-openstack update so this blocks nothing.

**Pull request merged**
