### PR TITLE
swift: install keystonemiddleware package in case of keystone auth

### PR DESCRIPTION
**Pull request by aplanas**
switf-proxy can be configured with keystone auth. Paste will try
to load the authtoken filter_factory, that resides in the package
python-keystonemiddleware.

Without this package, the service proxy-swift will fail to load
with an error:

ImportError: No module named keystonemiddleware.auth_token

### CODE REVIEW

**Comment by rsalevsky** [comment]
Can you explain in the commit message why this is required?

**Comment by aplanas** [comment]
* Add explanation in the commit message

**Comment by rsalevsky** [comment]
+1

**Comment by aplanas** [comment]
* Add a commit to fix bsc#989683

**Comment by nicolasbock** [comment]
+1

**Comment by dirkmueller** [comment]
Ignoring LGTM..

**Comment by aspiers** [comment]
I'm not sure why the "swift: remove swift-dispersion-populate timeout" commit was piggy-backed onto this PR - to me it looks like an independent topic. Unfortunately it has caused quite a lot of breakage of the gate. Also in general I think any execution of a non-trivial command which redirects both STDOUT and STDERR to `/dev/null` is a really bad idea.  As a result, in this case the gate is breaking and we have no idea why because the error is being thrown away.  So in the future please don't do that.

**Comment by aplanas** [comment]
As commented, the fail is in the only_if, not in command.

**Pull request merged**
