### PR TITLE
Minimal fixes for being able to deploy Liberty

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM codewise

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
+1: Tested in C16 with Liberty

**Comment by toabctl** [comment]
> +1: Tested in C16 with Liberty

@aplanas were the tempest tests successful? In CI run, tempest failed...

**Comment by aplanas** [comment]
@toabctl I am checking service by service to evaluate this: https://github.com/crowbar/crowbar-openstack/pull/65 https://github.com/crowbar/crowbar-openstack/pull/63 https://github.com/crowbar/crowbar-openstack/pull/61 https://github.com/crowbar/crowbar-openstack/pull/60 https://github.com/crowbar/crowbar-openstack/pull/58

**Comment by toabctl** [comment]
+1

**Pull request merged**
