### PR TITLE
Fix ceilometer role renaming for HA

### PR DESCRIPTION
**Pull request by rhafer**
There can be multiple nodes with the ceilometer-cagent role. Update all of them
not only the first.

### CODE REVIEW

**Comment by jsuchome** [comment]
+1 (is the role renaming in nova fixed the same way?)

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by rhafer** [comment]
> is the role renaming in nova fixed the same way

It was already accounting for multiple nodes.

**Pull request merged**
