### PR TITLE
tempest: update tempest.conf.erb to Liberty

### PR DESCRIPTION
**Pull request by toabctl**
This is a copy of the Liberty tempest.conf.sample
with our current modification.

### CODE REVIEW

**Comment by toabctl** [comment]
FYI: I haven't tested this yet.

**Comment by toabctl** [comment]
Initial smoke tests passed (but only 126 tests: ```Ran 126 tests in 952.512s```. not sure if that's correct)

**Comment by toabctl** [comment]
Result of a full tempest run has ```Ran 1372 tests in 7244.439s```

**Comment by mjura** [comment]
Could you check `api_v3` option once again, I see that it was 
```
# If false, skip all nova v3 tests. (boolean value)
api_v3 = <%= @nova_api_v3 ? 'true' : 'false' %>
```

**Comment by mjura** [comment]
Another option which I have found is `disable_ssl_certificate_validation`
```
# Set to True if using self-signed SSL certificates. (boolean value)
disable_ssl_certificate_validation = <%= @ssl_insecure ? 'true' : 'false' %>
```

**Comment by mjura** [comment]
Please check also `domain_name = Default`

**Comment by mjura** [comment]
And `deactivate_image = true`

**Comment by mjura** [comment]
To check `build_timeout = 2000`

**Comment by toabctl** [comment]
> And deactivate_image = true

@mjura That's already set

**Comment by toabctl** [comment]
> To check build_timeout = 2000

@mjura already set

**Comment by toabctl** [comment]
> And deactivate_image = true

@mjura already set

**Comment by toabctl** [comment]
> Could you check api_v3 option once again

@mjura: done in https://github.com/crowbar/crowbar-openstack/commit/fe10900614c03a0e919d361edfc7d04ca592c3a6

**Comment by toabctl** [comment]
> Another option which I have found is disable_ssl_certificate_validation

@mjura: done in https://github.com/crowbar/crowbar-openstack/commit/fe10900614c03a0e919d361edfc7d04ca592c3a6

**Comment by toabctl** [comment]
> Please check also domain_name = Default

@mjura: done in https://github.com/crowbar/crowbar-openstack/commit/fe10900614c03a0e919d361edfc7d04ca592c3a6

**Comment by toabctl** [comment]
@mjura any other comments or a +1?

**Comment by mjura** [comment]
If gating will be green, then +1

**Comment by vuntz** [comment]
In case there's a need for a new update to the template, can you change `<%=[^ ]` to `<%= ` (in many places, we're missing a space for readability). But only do it in case you need to update the template.

**Comment by vuntz** [comment]
`api_v3 = <%= @nova_api_v3 ? 'true' : 'false' %>` and `nova_api_v3: nova[:nova][:enable_v3_api],`

Not your fault, but the attribute is gone for nova. I'm not sure which tempest tests are still using this -- if this is like nova, this actually controls v2.1 testing and we want to always enable this. Otherwise, we should always disable it.

**Comment by vuntz** [comment]
Not strictly related to the config template, but to the move to liberty: iirc, there's some magic in tempest now to do the cleanup. Which means we could remove the tempest_cleanup.sh script / template too.

**Comment by vuntz** [comment]
Shouldn't we set [telemetry-feature-enabled] events to true?

**Comment by vuntz** [comment]
What about [volume-feature-enabled] bootable?

**Comment by vuntz** [comment]
> api_v3 = <%= @nova_api_v3 ? 'true' : 'false' %> and nova_api_v3: nova[:nova][:enable_v3_api],
> 
> Not your fault, but the attribute is gone for nova. I'm not sure which tempest tests are still using this -- if this is like nova, this actually controls v2.1 testing and we want to always enable this. Otherwise, we should always disable it.

I just realized the option is in [identity-feature-enabled]; so clearly we're not setting it correctly :-)

**Comment by vuntz** [comment]
`tenant_name = <%= @keystone_settings['default_tenant'] %>` used to be `tenant_name = <%= @comp_tenant %>`. Is the change intended?

**Comment by vuntz** [comment]
`password = <%= @comp_pass %>` got lost in [identity]

**Comment by vuntz** [comment]
Not sure if it's fine to have [compute] ssh_user not be changed to cirros. Can you confirm?

**Comment by vuntz** [comment]
Wondering out loud (not related to this PR, though): we don't change `#volume_device_name = vdb`, but maybe it's needed for xen?

**Comment by vuntz** [comment]
```
# Does Nova preserve preexisting ports from Neutron when deleting an
# instance? This should be set to True if testing Kilo+ Nova. (boolean
# value)
#preserve_ports = false
```
=> setting should be changed :-)

**Comment by toabctl** [comment]
@vuntz addressed all your comments (except removing the tempest_cleanup script) in https://github.com/crowbar/crowbar-openstack/commit/399cae8e0e92c7d969c455a22f83136f9d2337dd

**Comment by vuntz** [comment]
+1

Want me to create a followup card about the remaining comments (mostly the cleanup script and volume_device_name for xen)?

**Comment by toabctl** [comment]
> Want me to create a followup card about the remaining comments (mostly the cleanup script and volume_device_name for xen)?

Done: https://trello.com/c/LfO82kea/807-cleanup-tempest-barclamp

**Comment by toabctl** [comment]
@mjura still +1? Or any other comments?

**Comment by vuntz** [comment]
@toabctl in http://docs.openstack.org/kilo/config-reference/content/nova-conf-changes-kilo.html, I see that the ec2_path changed from /services/Cloud to /, so we might have to change ec2_url accordingly.

**Comment by toabctl** [comment]
> @toabctl in http://docs.openstack.org/kilo/config-reference/content/nova-conf-changes-kilo.html, I see that the ec2_path changed from /services/Cloud to /, so we might have to change ec2_url accordingly.

We still have /services/Cloud in our nova.conf . Should we postpone it until the nova.conf.erb is updated?

**Comment by toabctl** [comment]
Retested the latest config. ```Ran 1372 tests in 6858.053s ; FAILED (failures=10)```. Failures are S3 related and also telemetry notifications.

**Comment by toabctl** [comment]
The failing test is: ```# python -mtesttools.run -- tempest.api.telemetry.test_telemetry_notification_api.TelemetryNotificationAPITestJSON.test_check_nova_notification```. Gets a timeout (waiting for a notification). maybe something we have in the new nova.conf.erb ?

**Comment by vuntz** [comment]
> We still have /services/Cloud in our nova.conf . Should we postpone it until the nova.conf.erb is updated?

We have a commented out value, though. So the default is used, and the new default is `/` :-)

**Comment by vuntz** [comment]
@toabctl nearly sure the telemetry failure you're seeing exists before this PR.

**Comment by toabctl** [comment]
> We have a commented out value, though. So the default is used, and the new default is / :-)

Fixed in https://github.com/crowbar/crowbar-openstack/commit/a7a63826a5324ea9073bbe613172e41df92918ee

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
@toabctl can you remove the heat_machine_id_file varible now that it is no longer used?

**Comment by toabctl** [comment]
@dirkmueller done. @vuntz still +1 ?

**Comment by vuntz** [comment]
@toabctl this is a never-ending story, because now you can remove the remaining reference to `heat_test_image_name`

**Comment by toabctl** [comment]
@vuntz but can we stop here, merge it and continue with the cleanup in another PR?

**Comment by vuntz** [comment]
I'm fine with that, sure. My +1 is still valid in that case.

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
