### PR TITLE
glance: Fix glance-scrubber to work with insecure SSL for keystone

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aplanas** [comment]
Is documented [1], so I guess that is also a bug in some of the CONF in glance, that is not exporting the parameter in the configuration file? Maybe submit an upstream bug report?

[1] http://docs.openstack.org/developer/glance/configuring.html

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
> Maybe submit an upstream bug report?

Already did it: https://bugs.launchpad.net/glance/+bug/1548825

**Comment by dirkmueller** [comment]
the glance cookbook isn't using oslo config generator yet.

**Comment by dirkmueller** [comment]
+1

**Comment by dirkmueller** [comment]
hmm, this should also be set in glance-cache and glance-api.conf for consistency

**Comment by vuntz** [comment]
> hmm, this should also be set in glance-cache and glance-api.conf for consistency

Done in new commit.

**Comment by mjura** [comment]
+1

**Comment by vuntz** [comment]
@dirkmueller does the updated commit work for you?

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
