### PR TITLE
Revert "nova: Start virtlogd also for SLES 12.1 platform"

### PR DESCRIPTION
**Pull request by toabctl**
Reverts crowbar/crowbar-openstack#499

### CODE REVIEW

**Comment by toabctl** [comment]
Merge this when we switched to SP2

**Comment by jsuchome** [comment]
+1 once the switch is done

**Comment by dguitarbite** [comment]
:+1: Merge after the switch

**Comment by rsalevsky** [comment]
@toabctl Can we merge this?

**Comment by toabctl** [comment]
> @toabctl Can we merge this?

I general yes. But let's please wait until we have a working gate again and then let's check this PR. It currently doesn't hurt to have it in.

**Comment by toabctl** [comment]
rebased to trigger the PR testing...

**Pull request merged**
