### PR TITLE
nova: Do not setup NFS mount to controller when shared storage is manual (bsc#971546)

### PR DESCRIPTION
**Pull request by vuntz**
We specifically split the use_shared_instance_storage bit from
setup_shared_instance_storage to allow manually configured shared
storage, but we we were still configuring the NFS mount on the compute
nodes when the setup is manual.

### CODE REVIEW

**Comment by toabctl** [comment]
Duplicate "we we" in commit message

**Comment by vuntz** [comment]
> Duplicate "we we" in commit message

Fixed

**Comment by dirkmueller** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
3.0 backport at https://github.com/crowbar/crowbar-openstack/pull/340

**Pull request merged**
