### PR TITLE
nova: Add crowbar orchestration for compute HA

### PR DESCRIPTION
**Pull request by vuntz**
This is a bit tricky; if the commit messages are not clear enough, I'm happy to improve them -- just tell me how :-)

**Note:** This depends on ~~https://github.com/crowbar/crowbar-ha/pull/70~~, ~~https://github.com/crowbar/crowbar-core/pull/193~~ and ~~https://github.com/crowbar/crowbar-ha/pull/74~~

### CODE REVIEW

**Comment by mjura** [comment]
Hmmm gating tests are failing and it seems that it is related to this change

**Comment by vuntz** [comment]
> Hmmm gating tests are failing and it seems that it is related to this change

Yes: as mentioned in the description, this PR depends on a few others, and so gating can't be green without them.

**Comment by aspiers** [comment]
All commits except for the orchestration one look fine to me.  That one might be fine too, but I'm still wrapping my head around it on the plane ;-)  Please could you add this to the orchestration etherpad?

**Comment by vuntz** [comment]
> Please could you add this to the orchestration etherpad?

done

**Comment by dirkmueller** [comment]
LGTM (not reviewed in detail)

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
Gating failed due to changes in crowbar-core required for this not yet in the ISO.

**Comment by vuntz** [comment]
Rebased; only code change compared to before rebase is last commit.

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
