### PR TITLE
monasca: Filter out non-monitoring nodes on monasca dashboard

### PR DESCRIPTION
**Pull request by samirjorina**
Monasca Health Grafana dashbouard should only include monitoring nodes.
Use filtering by service=monitoring to achieve that.
Also fix disk usage graph.

### CODE REVIEW

**Comment by samirjorina** [comment]
Also requires backporting to stable/4.0

**Comment by toabctl** [comment]
@samirjorina typo in the commit msg (dashbouard)

**Comment by samirjorina** [comment]
Typo corrected

**Comment by toabctl** [comment]
@samirjorina needs a rebase. sorry

**Comment by samirjorina** [comment]
PR rebased

**Comment by toabctl** [comment]
Backport is https://github.com/crowbar/crowbar-openstack/pull/1052

**Pull request merged**
