### PR TITLE
 Check for existance of SSL certificate, generate if requested (bsc#959308)

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by dirkmueller** [comment]
completely untested (wip)

**Comment by vuntz** [comment]
Just checking: we don't generate the certificate in the horizon package anymore?

**Comment by dirkmueller** [comment]
@vuntz no, it was removed in order to not slowdown non-ssl deployments

**Comment by vmoravec** [comment]
Tested and works fine.

**Comment by kbaikov** [comment]
+1

**Comment by aplanas** [comment]
+1

**Pull request merged**
