### PR TITLE
tempest: fix lbaasv2 tests with Octavia lbaasv2-proxy service plugin (SOC-10907)

### PR DESCRIPTION
**Pull request by stefannica**
According to [1], if Octavia is deployed, the `lbaasv2-proxy` neutron service
plugin should replace the `lbaasv2` service plugin to allow users to continue
using the deprecated neutron API to manage Octavia load balancers.
However, some of the `neutron_lbaas.tests.tempest.v2.api` tempest test cases
no longer pass with the `lbaasv2-proxy` service plugin configured, mainly
because the regular neutron lbaas tempest test cases are not entirely
compatible with the Octavia API. Even if the Octavia API is backwards
compatible with the neutron LBaaS v2 API, there are runtime timing
considerations that these test cases don't cover, such as load balancer
state transitions.

To continue running these test cases, the lbaas tempest configuration needs
to be slightly changed to disable tracking the operational status of
load balancer objects (i.e. the `test_with_noop` option needs to be set).

With the `lbaasv2-proxy` neutron service plugin configured,
the Octavia health manager no longer needs the event streamer
to keep the Neutron and Octavia databases in sync, because
Octavia load balancers are only stored in the Octavia database.
In addition to that, the `queue_event_streamer` has a known issue
with memory leaks (also see [2] and [3]).

This PR also creates a tempest filter to be run against Octavia with the
lbaasv2-proxy service plugin. The following test cases are
black-listed because they are not compatible with the
Octavia lbaasv2-proxy service plugin:
    
 - neutron_lbaas.tests.tempest.v2.api.test_health_monitors_non_admin.
 TestHealthMonitors.test_list_health_monitors_two
   - lbaas-proxy doesn't handle the `http_method` attribute correctly
   - see https://jira.suse.com/browse/SOC-10965
    
 - neutron_lbaas.tests.tempest.v2.api.test_load_balancers_non_admin.
 LoadBalancersTestJSON.test_create_load_balancer_invalid_flavor_field
   - the concept of neutron service flavors doesn't yet have an Octavia
   counterpart in Rocky, so the lbaasv2-proxy service plugin cannot
   transparently convert these attributes
   - see https://blueprints.launchpad.net/octavia/+spec/octavia-lbaas-flavors
    
 - neutron_lbaas.tests.tempest.v2.api.test_load_balancers_non_admin.
 LoadBalancersTestJSON.test_update_load_balancer_missing*
   - these test cases update an existing load-balancer with an empty
   body (i.e. without actually changing anything)
   - this use case isn't correctly handled by the lbaasv2-proxy
   service plugin

 - neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.
 TestSessionPersistence.test_session_persistence
   - this test case updates an existing pool with a null
   session_persistence value 
   - this use case isn't correctly handled by the lbaasv2-proxy
   service plugin

[1] https://wiki.openstack.org/wiki/Neutron/LBaaS/Deprecation
[2] https://bugzilla.suse.com/show_bug.cgi?id=1154235
[3] https://bugzilla.redhat.com/show_bug.cgi?id=1631234

### CODE REVIEW

**Comment by stefannica** [comment]
Testing that all lbaas test cases pass with this PR with an ECP Crowbar deployment: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/566/pipeline

**Comment by stefannica** [comment]
rebased to include the SSL support for octavia-api

**Comment by stefannica** [comment]
> We need to see if using the event streamer for the sync will cause the same mem leak seen in SOC9 CLM. If it does we need to consider the proxy or using the "noop" streamer and provide appropriate cleanup steps.

@KeithMnemonic I agree. I'll run some tests tomorrow to confirm.

**Comment by stefannica** [comment]
> Testing that all lbaas test cases pass with this PR with an ECP Crowbar deployment: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/566/pipeline

Re-testing with https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/569/pipeline to include octavia-api SSL support

**Comment by stefannica** [comment]
> > We need to see if using the event streamer for the sync will cause the same mem leak seen in SOC9 CLM. If it does we need to consider the proxy or using the "noop" streamer and provide appropriate cleanup steps.
> 
> @KeithMnemonic I agree. I'll run some tests tomorrow to confirm.

I can confirm that the memleak also happens with Crowbar if the queue event streamer is configured. However, if we're using the `lbaasv2-proxy` service plugin, the event streamer is no longer required, so we can turn it off.

**Comment by stefannica** [comment]
Re-testing with: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/575/pipeline

**Comment by nicolasbock** [comment]
Are we going to go without the streamer then @stefannica ? Are you ok with that @KeithMnemonic ?

**Comment by stefannica** [comment]
> Are we going to go without the streamer then @stefannica ? Are you ok with that @KeithMnemonic ?

The streamer is only needed to sync the Octavia database with the Neutron database. When the streamer is active, Octavia is regularly sending RPC messages back to Neutron with status updates concerning configured load balancers. However, with the lbaasv2-proxy service plugin configured in, Neutron no longer keeps track of load balancers in its database, so there's no need for the streamer. 

In addition to that, in Crowbar, we never had Octavia available before, so we don't need to keep Octavia load balancers in the Neutron database as an intermediate migration step. In fact, we can't even switch the Neutron lbaas provider from haproxy to Octavia before we remove all existing haproxy load balancers.

**Comment by stefannica** [comment]
Testing with: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/579/pipeline

**Comment by stefannica** [comment]
The qa_crowbarsetup.sh smoke tempest is now pasing. Re-running tempest for the unified CI `smoke` and `lbaas-octavia` tempest test filters to check if they also pass: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar-tests/detail/openstack-crowbar-tests/88/pipeline

**Comment by stefannica** [comment]
Full re-test for this PR in combination with the corresponding [automation PR](https://github.com/SUSE-Cloud/automation/pull/3774): https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/586/pipeline

**Comment by stefannica** [comment]
> Full re-test for this PR in combination with the corresponding [automation PR](https://github.com/SUSE-Cloud/automation/pull/3774): https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/586/pipeline

And again, to correct for the latest CI failures: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/589/pipeline

**Comment by stefannica** [comment]
> > Full re-test for this PR in combination with the corresponding [automation PR](https://github.com/SUSE-Cloud/automation/pull/3774): https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/586/pipeline
> 
> And again, to correct for the latest CI failures: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/589/pipeline

And again (mariadb issue this time): https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/591/pipeline

**Comment by stefannica** [comment]
Black-listed another lbaas test case: `neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.TestSessionPersistence.test_session_persistence`, this one also because it tests an operation that is incompatible with the lbaasv2-proxy.

**Comment by stefannica** [comment]
Re-testing with: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/604/pipeline

**Pull request merged**
