### PR TITLE
postgresql: Use 9.4 for openSUSE

### PR DESCRIPTION
**Pull request by vuntz**
This is the latest version of postgresql in Leap.

### CODE REVIEW

**Comment by jsuchome** [comment]
+1 ... although, maybe you could add a comment to the code that it's for current Leap

**Comment by vuntz** [comment]
@jsuchome done

**Comment by jsuchome** [comment]
Thanks (+1 stays of course)

**Comment by rsalevsky** [comment]
+1

**Comment by dirkmueller** [comment]
:+1:

**Pull request merged**
