### PR TITLE
postgresql, rabbitmq, cinder, nova, ceilometer: Use new pacemaker_transaction LWRP to create pacemaker resources

### PR DESCRIPTION
**Pull request by vuntz**
This depends on https://github.com/crowbar/crowbar-ha/pull/46 (EDIT: already merged)

### CODE REVIEW

**Comment by vuntz** [comment]
Removing wip tag: worked well with manual testing.

**Comment by mjura** [comment]
Hmmm, in https://github.com/crowbar/crowbar-ha/pull/46#issue-120224127 it is comment
```
  action :update
  # this will never create anything, only converge an existing primitive to the right parameters
```
but in this change we overwrite all :create actions to :update

Could you clarify this, please.

**Comment by vuntz** [comment]
@mjura: that's the whole point, the creation itself is done by the new transaction resource :-) We want to create the resources in one transaction, to avoid racesz.

**Comment by aspiers** [comment]
Gate failed to apply keystone.

**Comment by jsuchome** [comment]
I've retriggered gating run and voila - it passes!

+1 for the code

**Comment by aspiers** [comment]
The gate does not test with `hacloud=1` so it doesn't tell us much at all.  This must be tested with `hacloud=1` before merging.

**Comment by abel-navarro** [comment]
Manually deployed this with `hacloud=1` and does it successfully. Now running smoke tempest tests.

**Comment by abel-navarro** [comment]
smoke tempest tests passed on an `hacloud=1` environment.

**Comment by vuntz** [comment]
@aspiers said he was fine merging this before leaving, so considering this as a second +1 and merging.

**Pull request merged**
