### PR TITLE
[cinder] Add rbd custom capabilities for Cinder RADOS backend, (bsc#961108)

### PR DESCRIPTION
**Pull request by mjura**
Depends on https://github.com/crowbar/crowbar-ceph/pull/32

And this is how it looks like

custom_caps

### CODE REVIEW

**Comment by mjura** [comment]
Depends on https://github.com/crowbar/crowbar-ceph/pull/32

**Comment by dirkmueller** [comment]
I am not sure we want this to be exposed to UI, since this is a temporary workaround for ephemeral-storage-on-rbd not implemented. (consider documentation and QA overheard for a user-visible option).

**Comment by mjura** [comment]
This change can be treated separately with https://github.com/crowbar/crowbar-ceph/pull/32

**Comment by mjura** [comment]
This is not needed any more, all changes were done in https://github.com/crowbar/crowbar-ceph/pull/32

**Pull request closed without merging**
