### PR TITLE
[UNTESTED] use the new locking API

### PR DESCRIPTION
**Pull request by aspiers**
https://github.com/crowbar/crowbar-core/pull/14 introduced a new OO-style locking API.

Supersedes https://github.com/crowbar/crowbar-openstack/pull/4

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by aspiers** [comment]
@rsalevsky In future please check before merging PRs marked `[UNTESTED]`.  Sometimes the gate check is not a good enough test.  Thanks!

**Comment by rsalevsky** [comment]
@aspiers The most of your PRs are untested, so please start testing that we can merge PRs fast. Otherwise they hanging around for days without a good reason.

**Comment by aspiers** [comment]
@rsalevsky I am testing as fast as I can, and they are hanging around for very good reasons.

**Comment by aspiers** [comment]
BTW I don't think there was any harm done in this case.  I just mentioned it for the future.

**Pull request merged**
