### PR TITLE
[4.0] Backport databag changes

### PR DESCRIPTION
**Pull request by Itxaka**
Backport of all the databag changes from master to 4.0.
https://trello.com/c/aGIWBgbn/19-use-data-bag-instead-of-node-searches

Follows the history of all the different changes and PR that we did.
Unfortunately we miscalculated and divided the card into too many different PRs which caused too many different commits, thus the 17 commits backported for this PR.

### CODE REVIEW

**Comment by Itxaka** [comment]
Missing https://github.com/crowbar/crowbar-openstack/pull/1124, blocked until that gets merged to master

**Comment by Itxaka** [comment]
[Backport Use Data Bags instead of node searches](https://trello.com/c/Bha08NBc/43-backport-use-data-bags-instead-of-node-searches)

**Comment by Itxaka** [comment]
Last change merged to master and backported to this PR, this should be ready to review!

**Comment by Itxaka** [comment]
@nicolasbock Its a PR that I forgot to squash before clicking merge, so it went as 4 different commits. As to have a more clean history I merged all those 4 commits into just one for the backport

**Comment by nicolasbock** [comment]
Thanks @Itxaka. I don't know if we have a policy on that, but if I understand the result of our discussions on squashing correctly then I think the consensus was that we shouldn't squash as part of a backport [[1]](https://github.com/crowbar/crowbar-ha/pull/221#issuecomment-324106208). Maybe @aspiers can add some information here. Thanks!

**Comment by Itxaka** [comment]
@nicolasbock Im guessing @aspiers will be ok with this, as the original merge was supposed to be just one commit, as it was just one logical change, and the problem there is that I wrongly merged it before squashing. Let see what he says here (I hope he is ok because I dont know how I can now remove that commit from the history of this PR cleanly!) :laughing:

**Comment by nicolasbock** [comment]
Sounds good @Itxaka. You do reference all of the squashed commits, so one can make the connection to master easily, which I think is the main point here.

**Comment by Itxaka** [comment]
@guangyee You are right, it was a bit outdated as I started the branch some time ago and keep updating it with new commits but without rebasing. Its now rebased to latest 4.0! Thanks!

**Comment by guangyee** [comment]
Tested the changed in my local environment. The proposals went through fine. However, I ran into some tempest failures at the "testsetup" stage. i.e.

{0} tempest.scenario.test_server_multinode.TestServerMultinode.test_schedule_to_all_nodes [73.022582s] ... FAILED
{0} tearDownClass (tempest.scenario.test_server_multinode.TestServerMultinode) [0.000000s] ... FAILED
{1} tempest.api.volume.test_volumes_actions.VolumesV2ActionsTest.test_attach_detach_volume_to_instance [294.540773s] ... FAILED
{1} tearDownClass (tempest.api.volume.test_volumes_actions.VolumesV2ActionsTest) [0.000000s] ... FAILED
{1} tempest.api.volume.test_volumes_get.VolumesV1GetTest.test_volume_create_get_update_delete [7.467748s] ... ok
{1} tempest.api.volume.test_volumes_get.VolumesV1GetTest.test_volume_create_get_update_delete_from_image [16.646058s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesV2ListTestJSON.test_volume_list [0.094506s] ... ok
{1} tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops [12.392548s] ... FAILED
{1} tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops [78.432962s] ... FAILED
{1} tearDownClass (tempest.scenario.test_server_basic_ops.TestServerBasicOps) [0.000000s] ... FAILED

Could be something related to my local environment. But I haven't had the time to investigate yet. But otherwise, the code looks good. I would say lets merge it if Mr. Jenkin's happy. I am not in the position to complain about any sort of coding style as I am not a Ruby expert at this point. :-)

**Pull request merged**
