### PR TITLE
aodh: Add config for alarm_history_ttl (bsc#1073703)

### PR DESCRIPTION
**Pull request by aplanas**
The alarm_history_ttl config option for aodh was
not previously configurable.

### CODE REVIEW

**Comment by aplanas** [comment]
As I cannot update the original PR (https://github.com/crowbar/crowbar-openstack/pull/1655) I open this instead. Is the full work from @cinerama70 with some of the concern addressed.

**Comment by aplanas** [comment]
[P2 Bug 1073703 - SOC7 L3: openstack-aodh-expirer.cron question](https://trello.com/c/aGbpX57n/648-p2-bug-1073703-soc7-l3-openstack-aodh-expirercron-question)

**Comment by stefannica** [comment]
Needs backport to SOC7 ? Looking at the bug report, it appears so.

**Comment by aplanas** [comment]
Backport here: https://github.com/crowbar/crowbar-openstack/pull/1689

**Pull request merged**
