### PR TITLE
[4.0] Set State Snapshot Transfer Settings

### PR DESCRIPTION
**Pull request by jsuchome**
Backport of https://github.com/crowbar/crowbar-openstack/pull/1171

### CODE REVIEW

**Comment by jhesketh** [comment]
Backport looks fine, but clearly we need to investigate rhafer's comment. I'm unsure how best to test backports, I suspect I need to learn a bit more about mkcloud.

I've also squashed the master PR if we want to replicate that here.

**Comment by jsuchome** [comment]
I'm unsure if that behavior is related to this PR

**Comment by jsuchome** [comment]
Rebased to latest vertion of original PR.

**Comment by jsuchome** [comment]
@rhafer @jhesketh Could we merge this? I think we've proved our latest problems are unrelated...

**Comment by jsuchome** [comment]
[P11 galera config: Find the best value for SST](https://trello.com/c/27Q5XW7K/28-p11-galera-config-find-the-best-value-for-sst)

**Pull request merged**
