### PR TITLE
trove: Fix config file path

### PR DESCRIPTION
**Pull request by toabctl**
Commit dfb322935fca7 switched to the new config file paths but also
changed the common config file /etc/trove/trove.conf to
/etc/trove/trove-api.conf.d/100-trove-api.conf which seems not to work.

### CODE REVIEW

**Comment by toabctl** [comment]
UNTESTED!

**Comment by Itxaka** [comment]
I dont really think this is the real issue.

Deploying a clean machine with no trove and then deploying trove leaves it in a wrong state due the error mentioned on irc: `20046 ERROR root NoSuchTableError: instances`

This can be fixed by running `trove-manage --config-file /etc/trove/trove-api.conf.d/100-trove-api.conf db_sync`

After that, trove-api/conductor/taskmanager start with no issues. 

Furthermore, I re-tested that the trove binaries pick the override config file and they work, so this is pointing to a different issue, maybe during the chef-run?

**Comment by Itxaka** [comment]
oh my gooood, another dumb mistake on my part:


from the original commit:
```
execute "trove-manage db sync" do
  command "trove-manage --config-file #{node[:trove][:api][:config_file]} db_sync"
  user node[:trove][:user]
  group node[:trove][:group]
  action :nothing
  only_if { !node[:trove][:db_synced] }
end
```

Action :nothing is WRONG! Thats the real issue, this could get closed.

**Comment by dirkmueller** [comment]
hopefully we don't need this anymore

**Pull request closed without merging**
