### PR TITLE
Add Pure Storage FlashArray config to cinder barclamp

### PR DESCRIPTION
**Pull request by sdodsley**
Adds config to the UI, locale, cinder.conf, cinder schema
and add migration.

### CODE REVIEW

**Comment by toabctl** [comment]
@sdodsley thanks for the PR. any reason why you closed this directly?

**Comment by sdodsley** [comment]
Couldn't get houndci-bot to show me the errors it was finding so thought I'd just restart it, which resolved the issues

**Comment by jsuchome** [comment]
You could just amend old commit with the new one and hound will be restarted

**Comment by sdodsley** [comment]
I did that and it still didn't show me the 2 violations it was referring to.
Out of interest anyone know why the checks are stalling for the suse builds?

**Comment by toabctl** [comment]
> Out of interest anyone know why the checks are stalling for the suse builds?

tests are only run for PRs from people in a specific github group

**Pull request closed without merging**
