### PR TITLE
mysql: Fix undefined attribute 'ipaddress' (bsc#921015)

### PR DESCRIPTION
**Pull request by ovisan**
ipddress fails, needs to be node['ipaddress']

### CODE REVIEW

**Comment by toabctl** [comment]
Can you adjust the commit message? See ```git log``` how a commit message mentioning a bug looks like.

**Comment by ovisan** [comment]
@toabctl better?

**Comment by toabctl** [comment]
Better would be: ```mysql: Fix undefined attribute 'ipaddress' (bsc#921015)```

**Comment by ovisan** [comment]
@toabctl done

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
I will address the hound complain also, after that +1

**Comment by dirkmueller** [comment]
@ovisan can you please fix the houndci issue?

**Comment by ovisan** [comment]
@dirkmueller solved the houndci issue

**Comment by sayalilunkad** [comment]
+1

**Comment by vuntz** [comment]
+1

**Pull request merged**
