### PR TITLE
Restructured documentation on yml config

### PR DESCRIPTION
**Pull request by tboerger**
**Depends on https://github.com/vuntz/crowbar-core/pull/1 and https://github.com/crowbar/crowbar-core/pull/121**

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by mjura** [comment]
Rebuild gating tests

**Comment by mjura** [comment]
Hmmm gating is failing because of `crowbar_framework/config/locales/openstack/en.yml`. Please fix it

**Comment by tboerger** [comment]
> Hmmm gating is failing because of crowbar_framework/config/locales/openstack/en.yml. Please fix it

It's not really fixable because it conflicts with the branding patch.

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by tboerger** [comment]
So gating will always fail until we update the branding :)

**Pull request merged**
