### PR TITLE
Move db_dump_location attribute into database barclamp

### PR DESCRIPTION
**Pull request by jsuchome**
So it is not lost when we drop crowbar-config-default role.

This goes with https://github.com/crowbar/crowbar-core/pull/379

### CODE REVIEW

**Comment by jsuchome** [comment]
The problem with this solution is that user could actually change the value of location when reapplying database barclamp, which does not make sense

**Comment by vuntz** [comment]
@jsuchome does it have to be in the proposal? Couldn't it be a default attribute in the cookbook instead? So all nodes with that cookbook would have the attribute.

**Comment by jsuchome** [comment]
I actually like the alternative solution more https://github.com/crowbar/crowbar-core/pull/380 (still being tested)

**Comment by rhafer** [comment]
> Couldn't it be a default attribute in the cookbook instead?

@jsuchome Yeah, I also think that this is the better solution.

**Comment by jsuchome** [comment]
@rhafer The problem with having it as postgres/database cookbook default attribute is that it won't be available when I want to reach it from  crowbar-upgrade recipe (as no database recipe is run at the time I want to dump the database)

**Comment by rhafer** [comment]
@jsuchome Argh, right. I forgot about that :(

**Comment by rhafer** [comment]
@jsuchome I guess this and https://github.com/crowbar/crowbar-core/pull/379 and be closed, right?

**Pull request closed without merging**
