### PR TITLE
Enables deactivate image test

### PR DESCRIPTION
**Pull request by sayalilunkad**

### CODE REVIEW

**Comment by aspiers** [comment]
Please can you [update the commit message](http://blog.adamspiers.org/2015/03/24/why-and-how-to-correctly-amend-github-pull-requests/) to explain why this change is needed?  Thanks!

**Comment by dirkmueller** [comment]
+1, assuming it works :-)

**Comment by aspiers** [comment]
Thanks a lot for the update!  It now nicely explains what the change is, but still doesn't explain *why* it's needed.  It's important for the commit message to capture this as mentioned at the bottom of https://etherpad.nue.suse.com/p/cloud-pull-requests and also in this best practices document: https://wiki.openstack.org/wiki/GitCommitMessages#Information_in_commit_messages

(P.S. I guess I probably missed a Trello card somewhere which explains why the change is required, but even adding a link from the commit message to that would not be right since the Trello boards are internal and this is a F/OSS project.  That's covered by the "Do not assume the reviewer has access to external web services/site." point in the above wiki page.)

**Comment by dirkmueller** [comment]
@aspiers I think the git commit message explains why the change is needed (at least to me..).

**Comment by tboerger** [comment]
I'm fine with this commit message :+1:

**Comment by aspiers** [comment]
@dirkmueller Thanks, I misread it the first time. +1

**Pull request merged**
