### PR TITLE
monasca: Collect logs from monasca components

### PR DESCRIPTION
**Pull request by samirjorina**

### CODE REVIEW

**Comment by dirkmueller** [comment]
How do we avoid that there is a loop of some $action triggering a log message which triggers the kibana upload which then triggers the same log message again?

**Comment by samirjorina** [comment]
Log agent will not collect its own logs, which should ensure there is no 'logs-loop'. Not sure if there is any other case this may happen...

**Comment by samirjorina** [comment]
Commits squashed, commit message updated

**Comment by samirjorina** [comment]
Please do not merge it yet - I need to check one more thing.

**Pull request closed without merging**
