### PR TITLE
[5.0] tempest: Skip failing tests (SOC-9799)

### PR DESCRIPTION
**Pull request by gosipyan**
Manila see bug SOC-10395
Ceilometer see bug lp 1673738

### CODE REVIEW

**Comment by dirkmueller** [comment]
@gosipyan is this a backport from cloud9? then please add cherry-pick identifiers. if it isn't can we backpor tthe fixes from cloud9 to 8 rather than blacklisting testing?

**Comment by gosipyan** [comment]
@dirkmueller Currently in SOC9 dont have ceilometer run_filter enabled , regarding manila those tests are passing on SOC9 but failing in SOC8(also mkcloud fulltempest) I have created bug ,not aware of any fix that can be backported from SOC9

**Comment by dirkmueller** [comment]
@gosipyan right, ceilometer changed in cloud9, so thats explaining things. the manila part is actually being fixed by core services team..

**Comment by gosipyan** [comment]
@dirkmueller should i remove test skip now or after manila fix merged?do you ave any reference to fix?

**Pull request merged**
