### PR TITLE
Updates nova config template for Mitaka

### PR DESCRIPTION
**Pull request by sayalilunkad**

### CODE REVIEW

**Comment by toabctl** [comment]
# nova.conf.erb
## bindir

should be ```/usr/bin``` instead of ```/usr/local/bin```

## use_neutron
should be set to ```true```

## network_api_class
default is ok (default is ```nova.network.api.API```) because ```use_neutron``` is the value we need to set

## memcached_servers
Moved to ```[cache]memcache_servers``` . Maybe the format changed...

## cinder_insecure
This is no longer in the config file. Maybe a upstream bug and not in the config sample? Needs to be verified

**Comment by sayalilunkad** [comment]
>bindir

>should be /usr/bin instead of /usr/local/bin

>use_neutron

>should be set to true

>network_api_class

>default is ok (default is nova.network.api.API) because use_neutron is the value we need to set

Done
>memcached_servers

>Moved to [cache]memcache_servers . Maybe the format changed...

Added to [cache] section
>cinder_insecure

>This is no longer in the config file. Maybe a upstream bug and not in the config sample? Needs to be >verified

This needs to be fixed upstream. Created a bug report https://bugs.launchpad.net/nova/+bug/1615666

**Comment by toabctl** [comment]
@sayalilunkad You need to rebase this patch...

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
[cinder]
missing "insecure = <%= @cinder_insecure ? 'True' : 'False' %>"

**Comment by sayalilunkad** [comment]
@aplanas thanks, done!

**Comment by aplanas** [comment]
The s3 and ec2 information where is stored in mitaka? Or is in no use anymore?

**Comment by sayalilunkad** [comment]
@aplanas that has it's own package now, openstack-ecp-api iirc.

**Comment by aplanas** [comment]
@sayalilunkad makes sense, thanks!

+1

**Pull request merged**
