### PR TITLE
Constrain services to only run on controllers when doing HA (part 2)

### PR DESCRIPTION
**Pull request by vuntz**
This depends on ~~https://github.com/crowbar/crowbar-openstack/pull/175 and https://github.com/crowbar/crowbar-openstack/pull/177 and~~ https://github.com/crowbar/crowbar-ha/pull/56

### CODE REVIEW

**Comment by jsuchome** [comment]
Makes sense. +1

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
Rebased after merge of https://github.com/crowbar/crowbar-openstack/pull/177.

@jsuchome @aplanas I'm resetting your +1 counter.

**Comment by jsuchome** [comment]
Still +1

**Comment by aspiers** [comment]
I'm not sure why this is separate from #179?  But as with #179, I'm not keen on the introduction of several new `pacemaker_location` which all look very similar, since we already discussed the idea of fixing this with a Chef definition.

Also perhaps it would be worth rebasing again?  Quite a lot has been merged since this branch was created.

**Comment by vuntz** [comment]
> I'm not sure why this is separate from #179?

Because it was depending on another PR to update these cookbooks (it got merged since then). I can fold that PR back in the other, though.

**Comment by vuntz** [comment]
> I can fold that PR back in the other, though.

done

**Pull request closed without merging**
