### PR TITLE
Fix nova configuration for ZVM

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by mjura** [comment]
I think that we had patch for this driver which was moving this options to [zvm] section. In my opinion this specific options should stay in [zvm].

**Comment by dirkmueller** [comment]
@mjura the change is not only moving it to a different section (but I dropped the patch already since it wasn't workign anymore).

**Comment by vuntz** [comment]
+1 (not sure if you want to wait for the nova.conf rebase or not, though)

**Comment by aplanas** [comment]
+1

**Pull request merged**
