### PR TITLE
Allow to remove unused images after creating them

### PR DESCRIPTION
**Pull request by mjura**
This is fixing develcloud6 (4/linuxbridge/-t -s/all/ ) gating

### CODE REVIEW

**Comment by mmnelemane** [comment]
+1

**Comment by rhafer** [comment]
Could you explain in a little more detail why this helps? Doesn't setting this to 0 miss the whole purpose of the image cache?

While it might fix the ci failures, I am not really convinced this is the right fix.

**Comment by mjura** [comment]
test_volume_boot_pattern[compute,id-557cd2c2-4eb8-4dce-98be-f86765ff311b,image,smoke,volume]FAIL
> Could you explain in a little more detail why this helps? Doesn't setting this to 0 miss the whole purpose of the image cache?

This is because tempest test

```
Slowest 1 tests took 388.43 secs:
tempest.scenario.test_volume_boot_pattern.TestVolumeBootPatternV2
    test_volume_boot_pattern[compute,id-557cd2c2-4eb8-4dce-98be-f86765ff311b,image,smoke,volume]  388.43

======================================================================
FAIL: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPatternV2.test_volume_boot_pattern[compute,id-557cd2c2-4eb8-4dce-98be-f86765ff311b,image,smoke,volume]
----------------------------------------------------------------------
```

This test is failing, because tempest creates Ceph boot volume and early after this is trying to remove it and it is not possible, because default time for removing unused base images is set up for 86400 seconds and test is timeout.

**Comment by mjura** [comment]
@rhafer : As I can see this will be limited right now to `image_cache_manager_interval=2400`

**Comment by rhafer** [comment]
> As I can see this will be limited right now to image_cache_manager_interval=2400

That makes this change even more weird IMO. In that case it seems you were just lucky that the cache_manager ran inbetween. Or am I missunderstanding something here?

**Comment by mjura** [comment]
@rhafer : This option is weird at all, at it was added by VMware guy in https://review.openstack.org/#/c/59994 probably because VMware vCenter is caching this images in really awkward way.

**Comment by dirkmueller** [comment]
thanks, was about to suggest to not merge this..

**Comment by mjura** [comment]
This change is not valid any more

**Pull request closed without merging**
