### PR TITLE
Set clone-max metadata for clone resources

### PR DESCRIPTION
**Pull request by vuntz**
~~Depends on https://github.com/crowbar/crowbar-ha/pull/57~~

### CODE REVIEW

**Comment by jsuchome** [comment]
It actually depends on https://github.com/crowbar/crowbar-ha/pull/57 , not on 58 ...

**Comment by jsuchome** [comment]
+1

**Comment by vuntz** [comment]
Rebased

**Comment by aplanas** [comment]
+1 LGTM

**Comment by vuntz** [comment]
(no code change, just expanded a bit the commit message)

**Pull request merged**
