### PR TITLE
mysql: swap haproxy and cluster-check creation

### PR DESCRIPTION
**Pull request by AbelNavarro**
While working in the haproxy active/active feature, we found out that
galera clustercheck script was failing on non founder nodes. We believe
the cause is clustercheck trying to get the status of the service while
haproxy has not still been activated.

By swapping clustercheck and haproxy creation we aim to give time for
clustercheck to find the service active and thus avoid errors.

### CODE REVIEW

**Comment by AbelNavarro** [comment]
[Make haproxy active/active](https://trello.com/c/7oHIy01J/271-make-haproxy-active-active)

**Comment by jsuchome** [comment]
Isn't it contradicting https://github.com/crowbar/crowbar-openstack/pull/1627 ?

**Comment by AbelNavarro** [comment]
This seems to work together with https://github.com/crowbar/crowbar-ha/pull/304 . I had errors before but I couldn't find the exact cause for them, so I blame the environment. On new tries `galera` doesn't show anymore `pacemaker` fail errors.

**Comment by vuntz** [comment]
I'm wondering if there's a need for a sync mark after the haproxy config and before the pacemaker resources, though. I would expect that we would usually have that, and we're probably lucky that it works without this.

**Comment by vuntz** [comment]
> Once haproxy is up, it takes some time for haproxy to discover that the configured services are up and running. So it may happen that haproxy is up but then clustercheck to fail. Would it be fine to add a sleep after the sync mark?

I would think it's not needed, if only because with the sync mark, there will be a sleep in nearly all cases (and it's really only needed on the initial setup, not later).

**Comment by rhafer** [comment]
> While working in the haproxy active/active feature, we found out that
> galera clustercheck script was failing on non founder nodes. We believe
> the cause is clustercheck trying to get the status of the service while
> haproxy has not still been activated.

Can you give some more details on this? This sounds somewhat unexpected. IIRC clustercheck
should not be depending on haproxy to be up and running it should be contacting the mariadb instances
via the nodes admin IPs. Or am I missing your point?

**Comment by AbelNavarro** [comment]
@rhafer you are indeed right sir. My assumption was that `clustercheck` was listening on the haproxy port but I was wrong. Still I think it's worth trying to set the barrier and keep investigating, because this works sometimes (and some don't).

**Comment by rhafer** [comment]
> you are indeed right sir. My assumption was that clustercheck was listening on the haproxy port but I was wrong.

But then clustercheck needs to be started **before** haproxy. As haproxy needs to connect to it. So somehow I think this PR is wrong.

**Comment by AbelNavarro** [comment]
AFAIK haproxy does not connect to clustercheck. The service configured in haproxy connects to the database directly, so does clustercheck. In that sense the order of the two of them should be irrelevant.

Nevertheless, I never got clustercheck to work when it was configured before haproxy. It may be chance. I'm rebuilding the environment and will try to reproduce the problem. I'll ping you so you can take a look.

**Comment by rhafer** [comment]
> AFAIK haproxy does not connect to clustercheck. The service configured in haproxy connects to the database directly, so does clustercheck. In that sense the order of the two of them should be irrelevant.

The "httpchk"  configured for the "galera" backend in haproxy connects to clustercheck (port 5555). So if "clustercheck" is not running on a node, haproxy will consider mariadb on that node to be down and not direct any traffic to it. (That's the whole purpose of the clustercheck service)

**Comment by AbelNavarro** [comment]
The failure I'm observing at the moment is due to galera_monitor pacemaker resource failing, not clustercheck. The monitor ends up working properly but the pacemaker fail count is non-zero, so the deployment aborts. This may be a networking error during installation because rabbitmq has similar problems moments before.

About the clustercheck failure, I'd say I saw an error regarding that specific service, but cannot now. This means this patch may be unnecessary. I will try again only with https://github.com/crowbar/crowbar-ha/pull/304 which was the one showing this problem initially.

**Comment by AbelNavarro** [comment]
I have not seen again that clustercheck failure. About the pacemaker failcount it was due to a galera sync error that happened often. Thanks to @rhafer we could see that the problem was actually in the underlay rather in the change (https://github.com/crowbar/crowbar-ha/pull/304) itself. I'm then closing this PR because the change is considered unnecessary.

**Pull request closed without merging**
