### PR TITLE
bin: Add 3600s timeout to all crowbar subcommands

### PR DESCRIPTION
**Pull request by vuntz**
Some didn't have that, and I was seeing manila failing from time to
time.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by rsalevsky** [comment]
I think this change makes no sense right now. @tboerger Is working on the new crowbar client and this will replace this scripts.

**Comment by vuntz** [comment]
@rsalevsky except that this helps avoid issues in the CI now. And this doesn't conflict with the work on replacing the scripts.

**Comment by rsalevsky** [comment]
@vuntz Ah ok, yeah I have nothing against it at the changes are fine.

:+1:

**Comment by tboerger** [comment]
:+1:

**Pull request merged**
