### PR TITLE
Configure proper firewall_driver for ML2 specific agents

### PR DESCRIPTION
**Pull request by mjura**
For Linux Brigde should be
  `firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver`

For OpenvSwitch  should be
  `firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver`

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by mjura** [comment]
Gating is failing, because packages are not refreshed

**Comment by rhafer** [comment]
+1

**Comment by rossella** [comment]
Thanks! +1

**Pull request merged**
