### PR TITLE
Make token expiration configurable (bsc#941537)

### PR DESCRIPTION
**Pull request by dirkmueller**
Horizon session timeout is dependant also on the keystone
token timeout, which is "only" 1h by default. Raise this to
four hours and make it configurable via the hidden crowbar proposal.

### CODE REVIEW

**Comment by toabctl** [comment]
Failed due to https://github.com/SUSE-Cloud/crowbar-core/pull/3

**Comment by toabctl** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by toabctl** [comment]
@rsalevsky do you want to merge this or wait for M3 ?

**Comment by dguitarbite** [comment]
+1

**Pull request merged**
