### PR TITLE
[3.0] cookbooks: Use new node_search_with_cache helper

### PR DESCRIPTION
**Pull request by vuntz**
~~Requires https://github.com/crowbar/crowbar-core/pull/931 (merged)~~

~~Contains https://github.com/crowbar/crowbar-openstack/pull/681 (merged)~~

~~Contains https://github.com/crowbar/crowbar-openstack/pull/805 (merged)~~

Backport of https://github.com/crowbar/crowbar-openstack/pull/666

### CODE REVIEW

**Comment by vuntz** [comment]
> That PR contained another change, and although I might be missing something, but I haven't found that in the history:
> d848e5f
> Looking at the source code we might need that one as well?

I was initially thinking it's only for master, but upon digging, it's actually also valid for stable/3.0. Do you want me to backport that as a separate PR, or here?

**Comment by matelakat** [comment]
@vuntz Yes, I think it would make sense to have the backport of #391 separately, so this PR will only be dealing with the evil change.

**Comment by vuntz** [comment]
@matelakat I rebased on top of https://github.com/crowbar/crowbar-openstack/pull/805 (so it appears here also).

**Comment by vuntz** [comment]
We won't need that backport anymore.

**Pull request closed without merging**
