### PR TITLE
Re-write recipe for creating Magnum trustee domain

### PR DESCRIPTION
**Pull request by mjura**
During first run of chef-client options `trustee_domain_id`
and `trustee_domain_admin_id` were not saved in magnum.conf.
This was bacuse of order chef resources for ruby_block,
these attributes were saved after chef-client run ends.

### CODE REVIEW

**Comment by toabctl** [comment]
@mjura are you saying that https://github.com/crowbar/crowbar-openstack/pull/440 doesn't work?

**Comment by mmnelemane** [comment]
@mjura:  Just a couple of questions: 
Doesn't the template changes alone fix the problem of saving the trustee domain parameters into magnum.conf ? 
Are the changes in setup.rb (moving openstack commands out of the bash block) also  part of the fix OR is it a just a cleanup of the recipe ?

**Comment by mjura** [comment]
@toabctl: Changes https://github.com/crowbar/crowbar-openstack/pull/440 works too, problem is only with first run and because normally mkcloud is applying tempest after Magnum, there is second run which is fixing this issue. That's way this problem wasn't discovered before.

**Comment by mjura** [comment]
@mmnelemane: Moving out from bash block is also fix for this bug. Probably this same problem apply to Heat, but it requires more tests.

**Comment by mjura** [comment]
@mmnelemane: You are right changes in template `magnum.conf.rb` can be omitted.

**Comment by mjura** [comment]
@mmnelemane, @toabctl: Any comments from you? I would like to merge this change

**Comment by mmnelemane** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
