### PR TITLE
keystone: better keystone http/https change logic (bsc#1044266)

### PR DESCRIPTION
**Pull request by Itxaka**
Before this patch, we modified the role and saved it which
caused the crowbar-revision to inscrease, which could lead to
desynchronization when applying a barclamp to a subset of
the keystone-server nodes.

This patch avoid that by directly saving the endpoint information
to the keystone-server nodes after the chef run, plus as a side
effect simplifies the code by avoiding any role modification
before the chef run is done.

### CODE REVIEW

**Comment by Itxaka** [comment]
[Keystone's crowbar-revsion increasing after chef-client run](https://trello.com/c/triedtIl/322-keystones-crowbar-revsion-increasing-after-chef-client-run)

**Comment by Itxaka** [comment]
Tested on non-HA and works, deploying HA env to test.

Also, wow, hound didnt complain, thats gotta be a first for me! :dog:

**Comment by cmurphy** [comment]
Is this the fix for the ceph synchronization problem?

**Comment by jsuchome** [comment]
That ha job fails in manila deployment, because there's no ceph-mds role. This is quite complicated in current SOC8 code ... and not relevant to this PR.

**Comment by aplanas** [comment]
@Itxaka can you try with this scenario? https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-ha-linuxbridge-x86_64/

**Comment by nicolasbock** [comment]
@Itxaka When I wrote the code to store the endpoints in the role, I was concerned with what would happen if a user would change out the set of Keystone servers and replace them. If the endpoint information is stored in the nodes, wouldn't that mean that this information is lost then?

**Comment by Itxaka** [comment]
> Is this the fix for the ceph synchronization problem?
@cmurphy yes, it may fix it :ok_hand: 

> @Itxaka can you try with this scenario? https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-ha-linuxbridge-x86_64/

@aplanas trigerred and added to the checklist :clap: 

> @Itxaka When I wrote the code to store the endpoints in the role, I was concerned with what would happen if a user would change out the set of Keystone servers and replace them. If the endpoint information is stored in the nodes, wouldn't that mean that this information is lost then?

@nicolasbock I would need more context to understand this correctly. Do you mean like a customer just trashing their keystone nodes and adding newer ones? I guess that in that case, yes it would be lost, but it would not matter as kesytone would be clean configured from zero so no changes needed to the endpoint, just the creation of newer endpoints.

**Comment by nicolasbock** [comment]
@Itxaka Yes, that's what I was thinking of. But I think you have a point. If the customer really replaces keystone then they would have to re-bootstrap the database anyhow. Thanks!

**Comment by Itxaka** [comment]
Actually the normal mkcloud job worked correctly: https://ci.suse.de/job/openstack-mkcloud/68664/

But for some reason, the jobs in github are mixed, probably a jenkins context issue :/

Will try to retrigger them properly.

**Comment by Itxaka** [comment]
swift was already deployed on the HA job so it seems that its working as expected, only that the jenkins context issue leads to look like it doesnt :)

**Comment by Itxaka** [comment]
```Error (105): No suitable node(s) for nova-compute-kvm found.``` :thinking:

**Comment by jsuchome** [comment]
> Error (105): No suitable node(s) for nova-compute-kvm found. ￼

That's likely because small number of nodes - 3 get used for ceph and there's noting left for compute. I was thinging https://github.com/SUSE-Cloud/automation/pull/2026 could fix it

**Comment by kbaikov** [comment]
@Itxaka  I applied this patch manually but i still get the error on applying swift barclamp: 

RuntimeError: crowbar-pacemaker_sync_mark[sync-swift_before_ha] (swift::proxy_ha line 29) had an error: RuntimeError: Some cluster nodes didn't set swift_before_ha to 14!

This is develcloud7. It is currently installed on qa4 hardware, if you are interested in debugging that please ssh to 10.162.66.10 and take a look.

Thanks.

**Comment by Itxaka** [comment]
@kbaikov After checking it out it seems a completely different issue :)

**Pull request merged**
