### PR TITLE
keystone: Don't get in the way when having multiple regions (bsc#1012108)

### PR DESCRIPTION
**Pull request by bhdn**
These changes allow administrators to set up manually multiple keystone endpoints for different regions. Otherwise crowbar would replace any endpoint of the same service with the one used in the current deployment, defeating the approach for a multi region deployment.

### CODE REVIEW

**Comment by bhdn** [comment]
Should I do something about these indentation complaints from Hound?

**Comment by dirkmueller** [comment]
@bhdn yes please, would be nice to keep this consistently indented

**Comment by bhdn** [comment]
Do you have any reservations about the behavior of this patch? I would like to prepare a PTF out of it.

**Comment by bhdn** [comment]
[P2: bsc#1012108: L3: add multiregion support for keystone](https://trello.com/c/v5iPUm3l/196-p2-bsc-1012108-l3-add-multiregion-support-for-keystone)

**Comment by bhdn** [comment]
[P2: bsc#1012108: L3: add multiregion support for keystone](https://trello.com/c/v5iPUm3l/196-p2-bsc-1012108-l3-add-multiregion-support-for-keystone)

**Comment by toabctl** [comment]
triggered CI

**Comment by cmurphy** [comment]
This bug is reported for SOC6. I can't reproduce the issue on SOC7, I think because we now use keystone-manage bootstrap and only trigger that once. Should this just be proposed to stable/3.0?

**Comment by bhdn** [comment]
Ok, I will create a new PR for that.

**Comment by vuntz** [comment]
> This bug is reported for SOC6. I can't reproduce the issue on SOC7, I think because we now use keystone-manage bootstrap and only trigger that once. Should this just be proposed to stable/3.0?

We actually still need that for stable/4.0 & master: this is a patch that enables people to do multiregion in case they know what they are doing.

**Comment by rsalevsky** [comment]
@bhdn Please rebase.

**Comment by dirkmueller** [comment]
@bhdn needs rebase ..

**Comment by rsalevsky** [comment]
@cmurphy Could you maybe help rebasing this PR as you worked recently on the conflicting code?

**Comment by cmurphy** [comment]
@rsalevsky sure

**Comment by bhdn** [comment]
Please go ahead. The code has been refactored and I won't have the time to look at it now.

**Comment by cmurphy** [comment]
Done

**Comment by rsalevsky** [comment]
@cmurphy The HA gating failure looks related.

**Comment by cmurphy** [comment]
@vuntz do you remember the rationale behind f2e60631bdeba01bcc0be3367fe3cb7e3c267504? The address defaults to "0.0.0.0" and it is clearly not designed to handle the HA case, where my_admin_host uses a helper to get either the cluster domain name or node fqdn depending on the case.

**Comment by dirkmueller** [comment]
@cmurphy I bet this is supposed to enable a 2nd crowbar installation register "its" users against the first crowbar installation's keystone (so rather than using the 2nds crowbar internal keystone have it update stuff on the primary keystone that is actually managed by teh first crowbar). 

It does look like the patch is wrong / incomplete, the changes need to be moved inside the wrapper. maybe remove this 2nd patch and we rework it in a different PR? the first one should be mergeable as it is.

**Comment by cmurphy** [comment]
@dirkmueller done, and also saved the second commit in https://github.com/cmurphy/crowbar-openstack/tree/pr_817_backup

**Pull request closed without merging**
