### PR TITLE
swift: Minor cleanups

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by jsuchome** [comment]
+1

**Comment by toabctl** [comment]
+1 (gating run into a timeout - retriggering...)

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
@jsuchome @toabctl @aplanas I added one commit to fix the permissions of the config file; still +1?

**Comment by jsuchome** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
