### PR TITLE
[4.0] keystone: Use correct paths when syncing certs

### PR DESCRIPTION
**Pull request by skazi0**
The sync failed when certs and/or keys were located in non-default paths.

### CODE REVIEW

**Comment by JanZerebecki** [comment]
@ skazi0 found that this bug was uncovered by https://github.com/SUSE-Cloud/automation/commit/4194b0ee6fbe05305d17bca2166ca87fd5cefc02 from https://github.com/SUSE-Cloud/automation/pull/3194 .

**Comment by JanZerebecki** [comment]
This isn't needed for SOC8 nor 9, because of https://github.com/crowbar/crowbar-openstack/pull/1204 .

**Comment by JanZerebecki** [comment]
Responding to https://github.com/crowbar/crowbar-openstack/pull/2146#issuecomment-498393832 :
This PR is in response to ci ha job failing with:
```
Errno::ENOENT: ruby_block[synchronize signing keys for founder and remember them for non-HA case] (keystone::server line 347) had an error: Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/keystone/ssl/certs/ca.pem
```
E.g. in https://ci.suse.de/job/openstack-mkcloud/171079/parsed_console/ testing https://github.com/crowbar/crowbar-openstack/pull/2144 .

**Comment by JanZerebecki** [comment]
cmurphy pointed out in the comment linked above that the here modified lines are not about https, which means it changes it to the wrong certificates.
Maybe the postinst script calling pki_setup https://build.opensuse.org/package/view_file/Cloud:OpenStack:Newton/openstack-keystone/openstack-keystone.spec?expand=1 failed?

**Comment by skazi0** [comment]
@cmurphy @JanZerebecki ah, now I get it. I got confused because `node[:keystone][:ssl]` and `node[:keystone][:signing]` have the same values by default. I will change this PR but it will probably not work as automation scripts don't set those values correctly in `signing` section.

**Comment by skazi0** [comment]
Updated version uses `signing` section but https://github.com/SUSE-Cloud/automation/pull/3467 is needed before it could work.

**Comment by skazi0** [comment]
This PR was closed as the only commit here was moved to https://github.com/crowbar/crowbar-openstack/pull/2146 to avoid cross-PR dependencies in gating.

**Pull request closed without merging**
