### PR TITLE
[Newton+] glance/aodh/ceilometer: Use systemd resource class

### PR DESCRIPTION
**Pull request by toabctl**
Instead of using the service resource class, use directly systemd.
There may be some problems with the service resource class.

### CODE REVIEW

**Comment by toabctl** [comment]
Retriggered gate with HA and newtoncloud7

**Comment by aplanas** [comment]
Gating moves from neutron, but fails in horizon

**Comment by toabctl** [comment]
> cinder is missing, nova, magnum, sahara, kerysone and manila too

its not missing. the packages are still using sysv init scripts

**Comment by aplanas** [comment]
Ah OK, so service: for lsb: is working

**Comment by toabctl** [comment]
> Could you address the hound issues? Otherwise looks great!

@nicolasbock done

**Comment by aspiers** [comment]
Would have been helpful to mention that this partially reverts https://github.com/crowbar/crowbar-openstack/pull/564.  Also "There may be some problems with the service resource class" is very vague; can you please give more details? (including a bugzilla link if appropriate)

**Comment by aspiers** [comment]
@toabctl Still waiting for clarification on this. Maybe it was already given via another medium (e.g. email) but I can't find it - really it needs to be clarified here for future reference.

**Pull request merged**
