### PR TITLE
Use Cirros 0.3.4

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by nkrinner** [comment]
+1

**Comment by mjura** [comment]
Looks ok +1

**Comment by aplanas** [comment]
I still see in the packages (stemsmanagement:crowbar:master) 0.3.3 version (for CirrOS and docker)

**Comment by dirkmueller** [comment]
@aplanas I see 0.3.4 in D:C:6:S (otherwise the gating check wouldn't have succeeded)

**Pull request merged**
