### PR TITLE
Revert "nova: Skip neutron configuration on VMware compute nodes (bsc#966690)

### PR DESCRIPTION
**Pull request by mjura**
This reverts commit 5ff33ee4f720c7e9deed45bfe4be7ee2d2c76194.

### CODE REVIEW

**Comment by dirkmueller** [comment]
@mjura can you add a rationale to the revert git commit message on why the revert should be done? note that I'm not objecting to the revert, just want to undersatnd it..

**Comment by mjura** [comment]
@dirkmueller : I've updated commit message and more details you can find in https://github.com/crowbar/crowbar-openstack/pull/292#issuecomment-185735742

**Comment by dirkmueller** [comment]
thanks. +1

**Comment by dirkmueller** [comment]
(was part of the review of the other PR, so merging)

**Pull request merged**
