### PR TITLE
Update keystone.conf config template with Liberty

### PR DESCRIPTION
**Pull request by mjura**
Updating keystone.conf template config with OpenStack Liberty

### CODE REVIEW

**Comment by vuntz** [comment]
Can you update template-keystone.json with default values that have changed? See http://docs.openstack.org/draft/config-reference/content/keystone-conf-changes-liberty.html

**Comment by vuntz** [comment]
I'm a bit mixed on keeping the drivers for revoke and trust (and maybe others) commented out while we had them set explicitly before. If this changes upstream without us noticing, then this is bad. On the other hand, that's what we usually do. So maybe it's okay.

**Comment by vuntz** [comment]
Re:
```
<% if @signing_token_format == "PKI" %>
provider = pki
<%end %>
```
I'd prefer to have an explicit `else` for `uuid` since we're likely going to add support for something else (fernet?) soon.

**Comment by vuntz** [comment]
Wondering if we should set `notification_format` to `cadf`. Any opinion?

**Comment by mjura** [comment]
Let me answer on your questions:
- all options in `keystone.conf` template are with defaults 
- I think we should stay with upstream as close as we can, that's way we can keep default drivers
- I've updated `provider` option and added `uuid` but this makes no sense for me
- With `notification_format` we can stay also with `basic` option. I didn't hear about any billing system integration, so it makes no sense to change it
http://docs.openstack.org/developer/keystone/event_notifications.html

**Comment by mjura** [comment]
PR was rebased, gating was green

**Comment by vuntz** [comment]
> - all options in keystone.conf template are with defaults
> - I think we should stay with upstream as close as we can, that's way we can keep default drivers

Will re-check. I guess you missed my point about the default values in the template: we should move from keystone.foo.bar.sql.foo to just sql.

> - I've updated provider option and added uuid but this makes no sense for me
> - With notification_format we can stay also with basic option. I didn't hear about any billing system integration, so it makes no sense to change it http://docs.openstack.org/developer/keystone/event_notifications.html

This is not just for billing, but also for auditing. And there it matters quite a bit.

**Comment by mjura** [comment]
@vuntz : I've change for `[resource]` and `[role]` sections drivers from `<None>` to `sql`. Rest drivers are sql or setup by crowbar options.

`notification_format` still want to leave as basic. But I'm fine with everything.

**Comment by toabctl** [comment]
@mjura: I think in the attributes.rb file, ```default[:keystone][:identity][:driver]``` should be changed to ```sql```

**Comment by toabctl** [comment]
@mjura same for ```default[:keystone][:assignment][:driver]``` I think. And here also the ```<% if``` in keystone.conf.erb must be adjusted.

**Comment by toabctl** [comment]
@mjura https://github.com/mjura/crowbar-openstack/blob/keystone_liberty_conf/chef/cookbooks/keystone/templates/default/keystone.conf.erb#L926 must be adjusted due to https://github.com/mjura/crowbar-openstack/commit/1ed90d5dd51b6f7436636ba51576925ad23dc267

**Comment by mjura** [comment]
@toabctl : Thanks, I've changed default attributes
```
default[:keystone][:identity][:driver] 
default[:keystone][:assignment][:driver]
``` 
to `sql`

for `driver` in [assignment] section we could go with 
`
driver = <%= node[:keystone][:assignment][:driver] rescue "sql" %>
`

**Comment by mjura** [comment]
I've set up also
```
<% if node[:keystone][:assignment][:driver] == 'hybrid' %>
```

**Comment by mjura** [comment]
Rebased

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
Minor nitpick:
```
<% if @signing_token_format == "PKI" %>
provider = pki
<% else %>
provider = uuid
<%end %>
```

You should end the `<%` tags with `-%>`

**Comment by vuntz** [comment]
> I guess you missed my point about the default values in the template: we should move from keystone.foo.bar.sql.foo to just sql.

This is still valid, just do `git grep "keystone.*backends"` to find all the locations where it needs to be changed. I'm happy to have it done in a followup PR if it's tracked in the trello card, though.

**Comment by vuntz** [comment]
> Edit: the important ones I immediately see are user_attribute_ignore

This is still valid (this was about the default attributes of the barclamp).

**Comment by vuntz** [comment]
> `notification_format` still want to leave as basic

Can you explain why (so I get convinced ;-))?

**Comment by mjura** [comment]
Things which were done:
   - chef statements was fixed in couple places
   - default attributes for cookbook and barclamp were synchronize

**Comment by mjura** [comment]
>> notification_format still want to leave as basic
>Can you explain why (so I get convinced ;-))?

I think that the best would be that we don't use this notifications anywhere, so there is not need to modify default values. Or I am wrong and missed something.

**Comment by mjura** [comment]
> This is still valid, just do git grep "keystone.*backends" to find all the locations where it needs to be > changed. I'm happy to have it done in a followup PR if it's tracked in the trello card, though.

Follow up card was created

**Comment by mjura** [comment]
> Edit: note that this will also require a migration for the values that are in the proposal.

I added migration script which is changing defaults

**Comment by mjura** [comment]
@vuntz : Thank you for code-review, I think that I addressed all you comments.

I rebased this PR, let's wait for gating

**Comment by dirkmueller** [comment]
+1

**Comment by vuntz** [comment]
> >> notification_format still want to leave as basic
> 
>    > Can you explain why (so I get convinced ;-))?
> 
> I think that the best would be that we don't use this notifications anywhere, so there is not need to modify default values. Or I am wrong and missed something.

People can use the notifications for auditing purpose, and the additional details there are useful in this context. Now there might be downsides to changing the option, but unless the downsides are really bad, I think it's useful to change the default.

**Pull request merged**
