### PR TITLE
manila: Fix proposal dependencies (bnc#949253)

### PR DESCRIPTION
**Pull request by toabctl**
Manila's generic driver needs Nova, Glance, Cinder and
Neutron. Add all of them as proposal dependencies.

### CODE REVIEW

**Comment by toabctl** [comment]
> Not related with this PR, but the explicit dep with Neutron and Nova suggest that that Manilla needs to be, in the barclamp view, after Nova (now is after Cinder)

Done in https://github.com/crowbar/crowbar-openstack/commit/531592292cfde9dd102d6933e332f2d06c3141a6

**Comment by aplanas** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Gating failed because manila got queue, and it got queued because it didn't know which nova, cinder, glance and neutron proposal to look at. You probably need to add attributes to reference these proposals (like we do for keystone).

**Comment by toabctl** [comment]
@vuntz are you talking about something like https://github.com/crowbar/crowbar-openstack/blob/master/crowbar_framework/app/models/keystone_service.rb#L57 ?

**Comment by vuntz** [comment]
@toabctl oh, sorry, I was not clear. Something like https://github.com/crowbar/crowbar-openstack/blob/master/crowbar_framework/app/models/manila_service.rb#L88-L93

**Comment by toabctl** [comment]
@vuntz done in https://github.com/toabctl/crowbar-openstack/commit/7f974495a5d43f0611062afdd437cd9fd2db36c0

**Comment by vuntz** [comment]
@toabctl I believe we also need to add the new attributes to the schema and template, + a migration.

**Comment by toabctl** [comment]
@vuntz .ah. ok. adding dependencies is more complicated than I thought...

**Comment by toabctl** [comment]
@vuntz maybe now!? untested...

**Comment by vuntz** [comment]
Yep, looks good, let's see what gating says!

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
Still: +1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
