### PR TITLE
We do not need to load docker image explicitely,

### PR DESCRIPTION
**Pull request by jsuchome**
nova-docker can do it itself

### CODE REVIEW

**Comment by jsuchome** [comment]
Well.. unless there's a requirement that compute nodes do not have the access to the network...

**Comment by vuntz** [comment]
@jsuchome reading the code, they would download the image from glance and import it from there, or am I missing something? (so network access wouldn't matter)

**Comment by jsuchome** [comment]
@vuntz you mean in _pull_missing_image? I can see there's some docker API used, not glance, but I may be missing it...

**Comment by vuntz** [comment]
@jsuchome https://git.openstack.org/cgit/openstack/nova-docker/tree/novadocker/virt/docker/driver.py#n406

`images.fetch` is downloading from glance, as far as I understand.

**Comment by jsuchome** [comment]
Ah, it comes from nova.virt. Than it makes sense, OK.

**Comment by vuntz** [comment]
Anyway, assuming this works, +1 :-)

**Comment by dirkmueller** [comment]
LGTM

**Pull request merged**
