### PR TITLE
neutron: Switch to LBaaSv2

### PR DESCRIPTION
**Pull request by vuntz**
This is not experimental anymore since Liberty.

### CODE REVIEW

**Comment by toabctl** [comment]
commit msg: ```Switch to ...``` instead of ```Ship to``` ?

**Comment by vuntz** [comment]
> commit msg: Switch to ... instead of Ship to ?

Oops, thanks :-)

**Comment by mjura** [comment]
This change works fine!!! But as I have tested Magnum supports only lbaasv1 !!!
https://bugs.launchpad.net/puppet-magnum/+bug/1583024

**Comment by vuntz** [comment]
@mjura gah. So I'll just use the patch I have for the stable/3.0 branch that adds an option to pick between lbaasv1 and lbaasv2...

**Comment by mjura** [comment]
@vuntz: this is perfect idea

**Comment by mjura** [comment]
Btw. upstream patches for Magnum and LBAAS v2 are still not ready.

**Comment by toabctl** [comment]
> Btw. upstream patches for Magnum and LBAAS v2 are still not ready.

Is Magnum in Newton ready? Because LBaaSv1 was removed in Newton. See http://docs.openstack.org/releasenotes/neutron-lbaas/newton.html#new-features

**Comment by toabctl** [comment]
Looks like Magnum supports LBaaSv2 (which is the default for devstack)

**Comment by toabctl** [comment]
> @mjura gah. So I'll just use the patch I have for the stable/3.0 branch that adds an option to pick between lbaasv1 and lbaasv2...

@vuntz for SOC7 (on Newton) we don't need the possibility to select between v1 and v2. There is only v2.

**Comment by vuntz** [comment]
As discussed on IRC: we should take the first few commits of https://github.com/crowbar/crowbar-openstack/pull/513 if we want lbaasv2 quickly. The code here is just incomplete and some old version of the commits there.

**Pull request closed without merging**
