### PR TITLE
tempest: disable trove until bsc1018614 is fixed so we dont block all…

### PR DESCRIPTION
**Pull request by Itxaka**
… ci jobs

### CODE REVIEW

**Comment by Itxaka** [comment]
should be reverted once package fix is in and available[0]

[0] https://build.opensuse.org/request/show/449014

**Comment by vuntz** [comment]
Ah well, as long as you remember to revert this...

**Comment by aspiers** [comment]
Thanks for this.  BTW I'm not sure it's a good idea to assign to so many people, as we never want that many reviewers.  If you just want to notify people then it's enough to mention them in the description or a comment ...

**Comment by Itxaka** [comment]
@aspiers yeah sorry about that, was friday at 20:30 and was looking for a review like a teenager looks for pokemons, so I went a bit overboard in hopes someone was up and around :D

**Comment by aspiers** [comment]
@Itxaka LOL! No worries ;-)

**Pull request merged**
