### PR TITLE
/etc/sysctl.d/99-sysctl.conf is a symlink to /etc/sysctl.conf

### PR DESCRIPTION
**Pull request by rsalevsky**
We should really use the direct file instead of relying on a symlink.

### CODE REVIEW

**Comment by rsalevsky** [comment]
I'm not sure about this change. Since some days the symlink is gone and the CI fails.

**Comment by jsuchome** [comment]
See e.g. https://ci.suse.de/job/openstack-mkcloud/125743/ for the failure

**Comment by rsalevsky** [comment]
@jsuchome The file comes from aaa_base but for this package was no update since January. The symlink exists on the admin node but is not owned by any package; on the control nodes the symlink doesn't exist.

**Comment by jsuchome** [comment]
Yeah, I've found the origin of /etc/sysctl.conf. But who creates (created) the symlink is unclear

**Comment by aplanas** [comment]
I can see the fails in the CI, but for me is not clear if this is a wrong test package from SLE

**Comment by jsuchome** [comment]
@aplanas so do you see where is this coming from?

(Anyway I think that Rick and Abel are right and the patch would make sense even if the link would exist)

**Comment by jsuchome** [comment]
@aplanas oh, you've added the original code! Now you have to decide ;-)

**Pull request merged**
