### PR TITLE
Use consistent naming schema for OpenStack barclamps

### PR DESCRIPTION
**Pull request by toabctl**
OpenStack barclamp description follow the format:

"OpenStack projectname: description".

### CODE REVIEW

**Comment by vuntz** [comment]
Actually, I think the current way was done because of the trademark guidelines for OpenStack and what was (back then) the core modules of OpenStack (even new modules in the releases were not part of the trademark policy).

I'm not sure how things are today...

**Comment by toabctl** [comment]
Hm. According to the release notes, all have "OpenStack" as prefix. See https://wiki.openstack.org/wiki/ReleaseNotes/Liberty . Also all the projects are listed here: http://docs.openstack.org/releases/releases/liberty.html .

**Comment by vuntz** [comment]
@toabctl that's great, thanks for checking! Can you remove the "Module" bit from the string also? :-)

**Comment by dirkmueller** [comment]
+1 if @vuntz comment is addressed as well..

**Comment by mjura** [comment]
Change is OK and has not influence on gating
+1

**Comment by toabctl** [comment]
> Can you remove the "Module" bit from the string also? :-)

Done in https://github.com/toabctl/crowbar-openstack/commit/a028e57a205bbeba203d7c11d17b5026415f27d4

**Comment by dirkmueller** [comment]
can you do that also in the other *.yml files?

**Comment by toabctl** [comment]
> can you do that also in the other *.yml files?

What exaclty?

**Comment by dirkmueller** [comment]
@toabctl removal of "Module" and addition of "OpenStack".

**Comment by toabctl** [comment]
> removal of "Module" and addition of "OpenStack".

@dirkmueller where exaclty? I have now:
```
$ grep -i description *.yml
ceilometer.yml:  description: 'OpenStack Telemetry: Measurements collection for monitoring and metering'
cinder.yml:  description: 'OpenStack Block Storage: Management of volumes (persistent block level storage)'
database.yml:  description: 'Resource for accessing Database Servers'
glance.yml:  description: 'OpenStack Image Service: Discovery, registration and delivery services for virtual machine images'
heat.yml:  description: 'OpenStack Orchestration: Orchestration engine for composite cloud applications'
horizon.yml:  description: 'OpenStack Dashboard: Web User Interface to access, provision and automate Cloud-based resources'
keystone.yml:  description: 'OpenStack Identity: Authentication and authorization service'
manila.yml:  description: 'OpenStack File Share: Management of shared filesystems'
neutron.yml:  description: 'OpenStack Networking: Pluggable, scalable, API-driven network and IP management'
nova.yml:  description: 'OpenStack Compute: Provision and manage large network of virtual machines'
openstack.yml:  description: 'OpenStack Project has multiple components'
rabbitmq.yml:  description: 'AMQP Messaging Middleware: robust enterprise messaging system'
swift.yml:  description: 'OpenStack Object Storage: Scale-out object store'
tempest.yml:  description: 'OpenStack Integration Test Suite'
trove.yml:  description: 'OpenStack Database: Scalable and reliable Database-as-a-Service provisioning'
```

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
Gating failure is unrelated. @dirkmueller fine with merging it?

**Comment by dirkmueller** [comment]
@toabctl sorry, my fault. it looks good, thanks

**Pull request merged**
