### PR TITLE
Look into crowbar wall for network interfaces.

### PR DESCRIPTION
**Pull request by jsuchome**
We are only interested in interfaces managed by crowbar

An alternative to https://github.com/crowbar/crowbar-openstack/pull/476

### CODE REVIEW

**Comment by rhafer** [comment]
+1

Though I think the whole IP address handling in the swift cookbook would benefit from some cleanup. To me it seems as if ```Swift::Evaluator.get_ip_by_type``` is not needed any longer and could be replaced with ```Chef::Recipe::Barclamp::Inventory.get_network_by_type``` . That would also make the interface lookup a lot easier as well. However this would require changes in a few other places. I'll add a card to the back log for it.

**Comment by abel-navarro** [comment]
@jsuchome since #476 was already merged, can we close this one?

**Comment by jsuchome** [comment]
Yes... unless this is the better solution. What do you think? And @rhafer, do you remember?

**Comment by rhafer** [comment]
@jsuchome I think this is the better solution. Because ```crowbar_wall``` only contains the interfaces that are managed by crowbar. And AFAIK the interfaces there always have the ```addresses``` key.

**Comment by jsuchome** [comment]
@abel-navarro can you approve this so we can merge it?

**Comment by abel-navarro** [comment]
+1

**Pull request merged**
