### PR TITLE
swift: Fix check for running dispersion or not

### PR DESCRIPTION
**Pull request by vuntz**
It was not using the right API version nor the right auth URL.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by jsuchome** [comment]
That `populate-dispersion` call cannot read /etc/swift/dispersion.conf

**Comment by jsuchome** [comment]
`group node[:swift][:group]` in `populate-dispersion` resource seems to help

**Comment by jsuchome** [comment]
+1

**Comment by aplanas** [comment]
+1

**Pull request merged**
