### PR TITLE
Fix config group of the ZVM related options

### PR DESCRIPTION
**Pull request by dirkmueller**
Those need to be in the [DEFAULT] section.

### CODE REVIEW

**Comment by vuntz** [comment]
+1 (although maybe it'd be simpler to just move the whole block of options to the existing section, since this bit is not upstream (iirc).

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
@dirkmueller is it intended that the nova.conf change is huge? (github can't display it)

**Comment by toabctl** [comment]
> (github can't display it)

@vuntz I see the change in github.

**Comment by toabctl** [comment]
+1 (but untested)

**Comment by vuntz** [comment]
> > (github can't display it)
> 
> @vuntz I see the change in github.

I can see the other changes, but not the ones to nova.conf.erb:

> 1,740 additions, 1,741 deletions not shown because the diff is too large. Please use a local Git client to view these changes. 

And when I do a local diff, the diff is indeed huge.

**Comment by vuntz** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
