### PR TITLE
[neutron][Cisco ACI]: Multiple VMM domain support (SOC - 10471)

### PR DESCRIPTION
**Pull request by vvaradhan**
This PR enables the following feature for Cisco ACI:

Allows Crowbar configuration for enabling multiple VMM domain features for ACI. It was painful for the customer to change in the config file manually and avoid the chef-client from overriding the config.  Both KVM and VMWare based VMM domains can be configured using this feature.  

Each [apic_vmdom:<vmm_domain_name>] corresponds to a VMM configuration. In these sections, [apic] configurations can be overridden for more granular infrastructure sharing.
What is configured in the [apic] sharing will be the default used in case a more specific configuration is missing for the domain.

For example:

[apic_vmdom:soc_kvm_domain]
vlan_ranges=1000:2000

[apic_vmdom:soc_vmware_domain]
apic_vmm_type=vmware
enable_optimized_dhcp=false
enable_optimized_metadata=false

In case of a VMWare based VMM domain, the respective VMM domain MUST be created in APIC prior to configuring in neutron.  For KVM, neutron will create the VMM domain if not already created.

Note: The intended target of this PR is Cloud 7 and is updated here due to the standard process being followed for all PRs (master-update followed by cloud 7 backport). The tests were only done for Cloud 7 based deployments.

### CODE REVIEW

**Comment by rsalevsky** [comment]
Needs rebase

**Comment by vuntz** [comment]
@mmnelemane have you checked this out?

**Comment by mmnelemane** [comment]
Rebased and multiple commits squashed to single commit with updated commit format and details.

**Comment by mmnelemane** [comment]
duplicate of https://github.com/crowbar/crowbar-openstack/pull/2227 which is based on the latest fixes and changes.

**Pull request closed without merging**
