### PR TITLE
[stable/3.0] backport #416

### PR DESCRIPTION
**Pull request by mmnelemane**
Support Cisco APIC integration on Cloud6.

### CODE REVIEW

**Comment by rsalevsky** [comment]
Does this require new packages?

**Comment by mmnelemane** [comment]
@rsalevsky: yes.. it requires new packages. That should not cause problem because we have not yet enabled it from crowbar_framework. Some ovs fixes are required (from Cisco) before we enable the feature from crowbar_framework. This PR is just to make sure the code is available for demos on Cloud6 whenever some customer needs.

**Comment by dirkmueller** [comment]
+1

**Comment by rsalevsky** [comment]
@mmnelemane Thanks for clarification, please ping me when you enable it in crowbar.

+1

**Pull request merged**
