### PR TITLE
Improve LBaaS UI in crowbar

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by rsalevsky** [comment]
Do you have a screenshot from the improved UI? This will make the review easier.

**Comment by vuntz** [comment]
@rsalevsky:

capture du 2017-01-12 16-59-34

**Comment by dirkmueller** [comment]
Looks much better, thanks. do we want to remove the use_lbaas option from UI ? I don't think we need to expose this, since there is no obvious downside of enabling it and its enabled anyway by default.

**Comment by vuntz** [comment]
> do we want to remove the use_lbaas option from UI ? I don't think we need to expose this, since there is no obvious downside of enabling it and its enabled anyway by default.

Good point, and I agree. Done.

**Pull request merged**
