### PR TITLE
swift: Fix ring builder parser to be compatible with both Juno & Liberty

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by vuntz** [comment]
For the record: I can't fix the remaining hound issues as these are long lines that are there for a reason (existing output of a command).

**Comment by vuntz** [comment]
For some reason, hound is not reporting here...

**Comment by aplanas** [comment]
No fully tested, but +1

**Comment by jsuchome** [comment]
+1 (not tested, but the code looks correct)

**Pull request merged**
