### PR TITLE
Run syntaxcheck with warnings enabled

### PR DESCRIPTION
**Pull request by dirkmueller**
That gives some useful hints on what could be improved
as well.

### CODE REVIEW

**Comment by mjura** [comment]
More logs and useful information is always good to have, but can you provide some example?

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
@mjura https://travis-ci.org/crowbar/crowbar-openstack/builds/115286313

**Comment by vuntz** [comment]
Given that we've merged this in all other repos, let's go ahead.

**Pull request merged**
