### PR TITLE
Use current API version for dispersion auth

### PR DESCRIPTION
**Pull request by jsuchome**

### CODE REVIEW

**Comment by aplanas** [comment]
According to the documentation is expected to work, but did you tested with 3.0?

+1

**Comment by jsuchome** [comment]
I did, and it works, unlike the current value of 2.0

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Hrm, was about to merge, but can you add the bug number to the commit?

**Comment by dirkmueller** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Comment by toabctl** [comment]
+1 (if you add the missing bug number)

**Pull request merged**
