### PR TITLE
Adds encoding (bsc#953786)

### PR DESCRIPTION
**Pull request by sayalilunkad**
Adding this allows to use non-ASCII characters
in config file for openstack-dashboard.

### CODE REVIEW

**Comment by aplanas** [comment]
Reading the bug report I see why this fix works, but I find the message text a bit confusing. Actually this will allow UTF8 strings in the configuration file, not in Horizon itself.

**Comment by aplanas** [comment]
+1 for the fix

**Comment by toabctl** [comment]
Can you propose this upstream so the local_settings.py.sample has the encoding set?

**Comment by toabctl** [comment]
but +1, too

**Comment by aplanas** [comment]
@sayalilunkad thanks to adjusting the commit message: +1

**Comment by sayalilunkad** [comment]
@toabctl thanks, have created the patch upstream https://review.openstack.org/#/c/281164/

**Comment by toabctl** [comment]
@sayalilunkad thanks!

**Comment by mjura** [comment]
+1

**Pull request merged**
