### PR TITLE
ceilometer: Allow enabling SSL with HA (bsc#1049153)

### PR DESCRIPTION
**Pull request by bhdn**

### CODE REVIEW

**Comment by nicolasbock** [comment]
The Travis-CI job is failing:

~~~
$ rvm use 2.1.0 --install --binary --fuzzy
ruby-2.1.0 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.1.0 do rvm gemset create ' first, or append '--create'.
The command "rvm use 2.1.0 --install --binary --fuzzy" failed and exited with 2 during .
~~~

I noticed that Travis has been upgrading their container OS to "Trusty". Could that be the problem? But then other PR's would fail this step as well. I'll check...

**Comment by stefannica** [comment]
@nicolasbock I have two PRs, #1069 and #1070 that are failing travis-ci in the same manner. Any ideas about how we can fix travis ?

**Comment by nicolasbock** [comment]
@stefannica I think the issue is the underlying version of the VM OS that Travis-CI is using. Have a look at https://github.com/crowbar/crowbar-openstack/pull/1073. This PR forces the VM back to `precise` and things work again as before.

**Comment by bhdn** [comment]
Sorry, I delete the branch by mistake.

**Pull request merged**
